### ISSUE TITLE
packer (validate) crash. 

### ISSUE THREAD

**Issue by asitbhattacharya** [mitchellh/packer#1955]
I'm new to packer. I was trying to build a ubuntu vm for virtualbox. I was following tutorial athttp://blog.codeship.com/packer-vagrant-tutorial/

command: 
================
$packer version
Packer v0.7.5

$packer validate itr1.json 
......
plugin exited before we could connect
2015/02/27 18:35:03 waiting for all plugin processes to complete...

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/mitchellh/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!

I could not attach template and crash log files. Getting error as:
    "Unfortunately, we don't support that file type.  Try again with a PNG, GIF, or JPG." 
So pasting the content of the packer template and crash log file here.

packer template (itr1.json):
========================
```json
{
    "description": "ubuntu-14.04.2-server-amd64 packer file",

    "min_packer_version": "0.7.5",

    "variables": {
    },

    "builders": [
        {
            "name": "virtualbox-ubuntu-14.04.2-server-amd64",
            "type": "virtualbox-iso",
            "iso_checksum": "83aabd8dcf1e8f469f3c72fff2375195",
            "iso_checksum_type": "md5",
            "iso_url": "software/ubuntu-14.04.2-server-amd64.iso",
            "ssh_username": "vagrant",
            "boot_command": [
                "<esc><esc><enter><wait>",
                "/install/vmlinuz noapic preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg <wait>",
                "debian-installer=en_US auto_locale=en_US kbd-chooser/method=us <wait>",
                "hostname={{ .Name }} <wait>",
                "fb=false debconf/frontend=noninteractive <wait>",
                "keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=USA keyboard-configuration/variant=USA console-setup/ask_detect=false <wait>",
                "initrd=/install/initrd.gz -- <enter><wait>"
            ],
            "boot_wait": "4s",
            "guest_additions_path": "VBoxGuestAdditions_{{.Version}}.iso",
            "guest_os_type": "Ubuntu_64",
            "headless": "false",
            "http_directory": "http",
            "shutdown_command": "echo 'shutdown -P now' > shutdown.sh; echo 'vagrant'|sudo -S sh 'shutdown.sh'",
            "ssh_password": "vagrant",
            "ssh_port": "22",
            "ssh_wait_timeout": "10000s",
            "vboxmanage": [
                [
                    "modifyvm",
                    "{{.Name}}",
                    "--memory",
                    "2048"
                ],
                [
                    "modifyvm",
                    "{{.Name}}",
                    "--cpus",
                    "4"
                ]
             ],
            "virtualbox_version_file": ".vbox_version"
        }
    ],

    "provisioners": [
        {
            "override": {
                "virtualbox-ubuntu-14.04.2-server-amd64": {
                    "execute_command": "echo 'vagrant' | sudo -S sh '{{ .Path }}'"
                }
            },
            "scripts": [
                "scripts/root_setup.sh"
            ],
            "type": "shell"
        },
        {
            "scripts": [
                "scripts/setup.sh"
            ],
            "type": "shell"
        }
    ], 

    "post-processors": [
        "vagrant"
    ]
}
```

```
packer crash log (crash.log):
=======================
2015/02/27 18:35:03 [INFO] Packer version: 0.7.5  9cd66feeacbd9cb318b72eb5ed59428c5b8c37ac+CHANGES
2015/02/27 18:35:03 Packer Target OS/Arch: darwin amd64
2015/02/27 18:35:03 Built with Go Version: go1.3.3
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: amazon-chroot = /usr/local/bin/packer-builder-amazon-chroot
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: amazon-ebs = /usr/local/bin/packer-builder-amazon-ebs
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: amazon-instance = /usr/local/bin/packer-builder-amazon-instance
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: digitalocean = /usr/local/bin/packer-builder-digitalocean
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: docker = /usr/local/bin/packer-builder-docker
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: googlecompute = /usr/local/bin/packer-builder-googlecompute
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: null = /usr/local/bin/packer-builder-null
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: openstack = /usr/local/bin/packer-builder-openstack
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: parallels-iso = /usr/local/bin/packer-builder-parallels-iso
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: parallels-pvm = /usr/local/bin/packer-builder-parallels-pvm
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: qemu = /usr/local/bin/packer-builder-qemu
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: virtualbox-iso = /usr/local/bin/packer-builder-virtualbox-iso
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: virtualbox-ovf = /usr/local/bin/packer-builder-virtualbox-ovf
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: vmware-iso = /usr/local/bin/packer-builder-vmware-iso
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: vmware-vmx = /usr/local/bin/packer-builder-vmware-vmx
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: atlas = /usr/local/bin/packer-post-processor-atlas
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: compress = /usr/local/bin/packer-post-processor-compress
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: docker-import = /usr/local/bin/packer-post-processor-docker-import
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: docker-push = /usr/local/bin/packer-post-processor-docker-push
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: docker-save = /usr/local/bin/packer-post-processor-docker-save
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: docker-tag = /usr/local/bin/packer-post-processor-docker-tag
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: vagrant = /usr/local/bin/packer-post-processor-vagrant
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: vagrant-cloud = /usr/local/bin/packer-post-processor-vagrant-cloud
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: vsphere = /usr/local/bin/packer-post-processor-vsphere
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: ansible-local = /usr/local/bin/packer-provisioner-ansible-local
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: chef-client = /usr/local/bin/packer-provisioner-chef-client
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: chef-solo = /usr/local/bin/packer-provisioner-chef-solo
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: file = /usr/local/bin/packer-provisioner-file
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: puppet-masterless = /usr/local/bin/packer-provisioner-puppet-masterless
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: puppet-server = /usr/local/bin/packer-provisioner-puppet-server
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: salt-masterless = /usr/local/bin/packer-provisioner-salt-masterless
2015/02/27 18:35:03 [DEBUG] Discoverd plugin: shell = /usr/local/bin/packer-provisioner-shell
2015/02/27 18:35:03 Detected home directory from env var: /Users/asit
2015/02/27 18:35:03 Detected home directory from env var: /Users/asit
2015/02/27 18:35:03 Attempting to open config file: /Users/asit/.packerconfig
2015/02/27 18:35:03 File doesn't exist, but doesn't need to. Ignoring.
2015/02/27 18:35:03 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[amazon-ebs:/usr/local/bin/packer-builder-amazon-ebs vmware-iso:/usr/local/bin/packer-builder-vmware-iso null:/usr/local/bin/packer-builder-null virtualbox-iso:/usr/local/bin/packer-builder-virtualbox-iso virtualbox-ovf:/usr/local/bin/packer-builder-virtualbox-ovf amazon-instance:/usr/local/bin/packer-builder-amazon-instance digitalocean:/usr/local/bin/packer-builder-digitalocean docker:/usr/local/bin/packer-builder-docker openstack:/usr/local/bin/packer-builder-openstack parallels-pvm:/usr/local/bin/packer-builder-parallels-pvm amazon-chroot:/usr/local/bin/packer-builder-amazon-chroot googlecompute:/usr/local/bin/packer-builder-googlecompute parallels-iso:/usr/local/bin/packer-builder-parallels-iso qemu:/usr/local/bin/packer-builder-qemu vmware-vmx:/usr/local/bin/packer-builder-vmware-vmx] PostProcessors:map[compress:/usr/local/bin/packer-post-processor-compress docker-push:/usr/local/bin/packer-post-processor-docker-push docker-save:/usr/local/bin/packer-post-processor-docker-save vagrant:/usr/local/bin/packer-post-processor-vagrant atlas:/usr/local/bin/packer-post-processor-atlas docker-import:/usr/local/bin/packer-post-processor-docker-import docker-tag:/usr/local/bin/packer-post-processor-docker-tag vagrant-cloud:/usr/local/bin/packer-post-processor-vagrant-cloud vsphere:/usr/local/bin/packer-post-processor-vsphere] Provisioners:map[chef-solo:/usr/local/bin/packer-provisioner-chef-solo file:/usr/local/bin/packer-provisioner-file puppet-masterless:/usr/local/bin/packer-provisioner-puppet-masterless puppet-server:/usr/local/bin/packer-provisioner-puppet-server salt-masterless:/usr/local/bin/packer-provisioner-salt-masterless shell:/usr/local/bin/packer-provisioner-shell ansible-local:/usr/local/bin/packer-provisioner-ansible-local chef-client:/usr/local/bin/packer-provisioner-chef-client]}
2015/02/27 18:35:03 Setting cache directory: /Users/asit/works/p-hpes-wcds/ops/packer_cache
2015/02/27 18:35:03 Detected home directory from env var: /Users/asit
2015/02/27 18:35:03 Reading template: itr1.json
2015/02/27 18:35:03 Creating build: virtualbox-ubuntu-14.04.2-server-amd64
2015/02/27 18:35:03 Loading builder: virtualbox-iso
2015/02/27 18:35:03 Creating plugin client for path: /usr/local/bin/packer-builder-virtualbox-iso
2015/02/27 18:35:03 Starting plugin: /usr/local/bin/packer-builder-virtualbox-iso []string{"/usr/local/bin/packer-builder-virtualbox-iso"}
2015/02/27 18:35:03 Waiting for RPC address for: /usr/local/bin/packer-builder-virtualbox-iso
2015/02/27 18:35:03 packer-builder-virtualbox-iso: panic: strconv.ParseInt: parsing "": invalid syntax
2015/02/27 18:35:03 packer-builder-virtualbox-iso: 
2015/02/27 18:35:03 packer-builder-virtualbox-iso: goroutine 16 [running]:
2015/02/27 18:35:03 packer-builder-virtualbox-iso: runtime.panic(0x40fea0, 0xc2080a6060)
2015/02/27 18:35:03 packer-builder-virtualbox-iso: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/panic.c:279 +0xf5
2015/02/27 18:35:03 packer-builder-virtualbox-iso: main.main()
2015/02/27 18:35:03 packer-builder-virtualbox-iso: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/plugin/builder-virtualbox-iso/main.go:11 +0x67
2015/02/27 18:35:03 packer-builder-virtualbox-iso: 
2015/02/27 18:35:03 packer-builder-virtualbox-iso: goroutine 19 [finalizer wait]:
2015/02/27 18:35:03 packer-builder-virtualbox-iso: runtime.park(0x14370, 0x737bf8, 0x736629)
2015/02/27 18:35:03 packer-builder-virtualbox-iso: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/proc.c:1369 +0x89
2015/02/27 18:35:03 packer-builder-virtualbox-iso: runtime.parkunlock(0x737bf8, 0x736629)
2015/02/27 18:35:03 packer-builder-virtualbox-iso: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/proc.c:1385 +0x3b
2015/02/27 18:35:03 packer-builder-virtualbox-iso: runfinq()
2015/02/27 18:35:03 packer-builder-virtualbox-iso: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/mgc0.c:2644 +0xcf
2015/02/27 18:35:03 packer-builder-virtualbox-iso: runtime.goexit()
2015/02/27 18:35:03 packer-builder-virtualbox-iso: 	/Users/mitchellh/code/3rdparty/go/src/pkg/runtime/proc.c:1445
2015/02/27 18:35:03 packer-builder-virtualbox-iso: 
2015/02/27 18:35:03 packer-builder-virtualbox-iso: goroutine 20 [syscall]:
2015/02/27 18:35:03 packer-builder-virtualbox-iso: os/signal.loop()
2015/02/27 18:35:03 packer-builder-virtualbox-iso: 	/Users/mitchellh/code/3rdparty/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
2015/02/27 18:35:03 packer-builder-virtualbox-iso: created by os/signal.init·1
2015/02/27 18:35:03 packer-builder-virtualbox-iso: 	/Users/mitchellh/code/3rdparty/go/src/pkg/os/signal/signal_unix.go:27 +0x32
2015/02/27 18:35:03 /usr/local/bin/packer-builder-virtualbox-iso: plugin process exited
2015/02/27 18:35:03 ui error: Failed to create build 'virtualbox-ubuntu-14.04.2-server-amd64': 

plugin exited before we could connect
2015/02/27 18:35:03 waiting for all plugin processes to complete...
```

**Comment by rickard-von-essen** [comment]
For some reson the _builder-virtualbox-iso_ plugin fails to connect to packer. Can you reproduce this? (I couldn't)

**Comment by asitbhattacharya** [comment]
Strangely, I could not reproduce it either! This time not only validate was successful, but the "packer build" command completed successfully and created a vagrant box.
I'm closing this issue.
