### ISSUE TITLE
OpenStack builder creates image with invalid kernel_id, ramdisk_id properties

### ISSUE THREAD

**Issue by jgoldschrafe** [mitchellh/packer#2132]
Running OpenStack Kilo on Ubuntu 14.04.

When Packer creates an image for OpenStack, it sets `kernel_id` and `ramdisk_id` properties on the image with values of `NULL`. The existence of these keys causes the following error when a user attempts to provision an instance based on the image:

    2015-05-22 21:49:10.809 13229 ERROR nova.compute.manager [req-dab93e02-ad7f-41c7-9485-6c0bbebc11ca - - - - -] [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15] Instance failed to spawn
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15] Traceback (most recent call last):
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 2442, in _build_resources
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     yield resources
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 2314, in _build_and_run_instance
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     block_device_info=block_device_info)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 2347, in spawn
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     admin_pass=admin_password)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 2745, in _create_image
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     instance, size, fallback_from_host)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 5875, in _try_fetch_image_cache
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     size=size)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/imagebackend.py", line 231, in cache
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     *args, **kwargs)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/imagebackend.py", line 727, in create_image
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     prepare_template(target=base, max_size=size, *args, **kwargs)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py", line 445, in inner
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     return f(*args, **kwargs)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/imagebackend.py", line 221, in fetch_func_sync
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     fetch_func(target=target, *args, **kwargs)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 2737, in clone_fallback_to_fetch
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     backend.clone(context, disk_images['image_id'])
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/imagebackend.py", line 752, in clone
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     include_locations=True)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/nova/image/api.py", line 93, in get
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     show_deleted=show_deleted)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/nova/image/glance.py", line 301, in show
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     _reraise_translated_image_exception(image_id)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/nova/image/glance.py", line 299, in show
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     image = self._client.call(context, version, 'get', image_id)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/nova/image/glance.py", line 219, in call
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     return getattr(client.images, method)(*args, **kwargs)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/glanceclient/v2/images.py", line 106, in get
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     return self.model(**body)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/warlock/core.py", line 32, in __init__
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     base_class.__init__(self, *args, **kwargs)
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]   File "/usr/lib/python2.7/dist-packages/warlock/model.py", line 35, in __init__
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     raise ValueError(str(exc))
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15] ValueError: None is not of type u'string'
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15] Failed validating u'type' in schema[u'properties'][u'ramdisk_id']:
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     {u'description': u'ID of image stored in Glance that should be used as the ramdisk when booting an AMI-style image.',
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]      u'is_base': False,
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]      u'pattern': u'^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$',
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]      u'type': u'string'}
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15] On instance[u'ramdisk_id']:
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]     None
    2015-05-22 21:49:10.809 13229 TRACE nova.compute.manager [instance: 8039a1e8-f73b-4b39-8442-426a8870ad15]

At this time, the only available workaround is to delete the fields from the MySQL database directly after the image creation completes.

**Comment by mitchellh** [comment]
I can't reproduce this... is this perhaps an OpenStack config or operational error?

As far as I can tell from referencing the Nova docs, I don't even have the ability to specify these fields when creating the image. I'm assuming they're supposed to be inherited from the server, and Packer doesn't specify it for that either (which works on every provider I've tried).
