### ISSUE TITLE
validate crashes

### ISSUE THREAD

**Issue by bmizerany** [mitchellh/packer#2139]
Validate will crash if there is an error building a "plugin" (not sure what that is).

Here is the culprit: https://github.com/mitchellh/packer/blob/master/command/validate.go#L60

Maybe you want to exit here or `continue`, but not add nil to `builds` because it causes the panic below when it calls `Run()`.

Here is the crash report:

```
2015/05/26 17:23:57 [INFO] Packer version: 0.7.5  
2015/05/26 17:23:57 Packer Target OS/Arch: darwin amd64
2015/05/26 17:23:57 Built with Go Version: devel +4b78c95 Wed Apr 29 19:25:10 2015 +0000
2015/05/26 17:23:57 Detected home directory from env var: /Users/bmizerany
2015/05/26 17:23:57 Detected home directory from env var: /Users/bmizerany
2015/05/26 17:23:57 Attempting to open config file: /Users/bmizerany/.packerconfig
2015/05/26 17:23:57 File doesn't exist, but doesn't need to. Ignoring.
2015/05/26 17:23:57 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[] PostProcessors:map[] Provisioners:map[]}
2015/05/26 17:23:57 Setting cache directory: /Users/bmizerany/src/github.com/bmizerany/backplane/packer_cache
2015/05/26 17:23:57 Detected home directory from env var: /Users/bmizerany
2015/05/26 17:23:57 Loading builder: amazon-ebs
2015/05/26 17:23:57 Builder not found: amazon-ebs
2015/05/26 17:23:57 ui error: Failed to initialize build 'amazon-ebs': builder type not found: amazon-ebs
2015/05/26 17:23:57 waiting for all plugin processes to complete...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x91367]

goroutine 1 [running]:
github.com/mitchellh/packer/command.(*ValidateCommand).Run(0xc208015270, 0xc20800a1d0, 0x1, 0x1, 0xc2080f0998)
	/Users/bmizerany/src/github.com/mitchellh/packer/command/validate.go:70 +0xa77
github.com/mitchellh/cli.(*CLI).Run(0xc2080170e0, 0xc2080170e0, 0x0, 0x0)
	/Users/bmizerany/src/github.com/mitchellh/cli/cli.go:100 +0x3f8
main.wrappedMain(0x0)
	/Users/bmizerany/src/github.com/mitchellh/packer/main.go:171 +0x1157
main.realMain(0x0)
	/Users/bmizerany/src/github.com/mitchellh/packer/main.go:90 +0xac0
main.main()
	/Users/bmizerany/src/github.com/mitchellh/packer/main.go:25 +0x1f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1670 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x3f

goroutine 7 [syscall]:
syscall.Syscall(0x3, 0x0, 0xc208126000, 0x8000, 0x2800035b11, 0x19, 0x1)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x0, 0xc208126000, 0x8000, 0x8000, 0xd00028, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:970 +0x62
syscall.Read(0x0, 0xc208126000, 0x8000, 0x8000, 0xc208126000, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:160 +0x54
os.(*File).read(0xc20802a008, 0xc208126000, 0x8000, 0x8000, 0x470f60, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:211 +0x82
os.(*File).Read(0xc20802a008, 0xc208126000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x8d
io.copyBuffer(0xba41c0, 0xc20802a0f0, 0xba4ae8, 0xc20802a008, 0xc208126000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:381 +0x24a
io.Copy(0xba41c0, 0xc20802a0f0, 0xba4ae8, 0xc20802a008, 0x5564e0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:351 +0x6b
main.setupStdin.func1(0xc20802a0f0, 0xc20802a008)
	/Users/bmizerany/src/github.com/mitchellh/packer/stdin.go:23 +0xb8
created by main.setupStdin
	/Users/bmizerany/src/github.com/mitchellh/packer/stdin.go:24 +0x7a

goroutine 8 [chan receive]:
main.setupStdin.func2(0xc20801a6c0, 0xc20802a0f0)
	/Users/bmizerany/src/github.com/mitchellh/packer/stdin.go:34 +0x98
created by main.setupStdin
	/Users/bmizerany/src/github.com/mitchellh/packer/stdin.go:36 +0x147

goroutine 9 [select]:
net/http.(*Transport).getConn(0xc208074090, 0xc2081500d0, 0x0, 0xc20815c1c0, 0x5, 0xc208156080, 0x20, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:549 +0x508
net/http.(*Transport).RoundTrip(0xc208074090, 0xc2081500d0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:228 +0x4af
net/http.send(0xc2081500d0, 0xba4440, 0xc208074090, 0x62, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:220 +0x4e1
net/http.(*Client).send(0x7e0040, 0xc2081500d0, 0x62, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:143 +0x15d
net/http.(*Client).doFollowingRedirects(0x7e0040, 0xc2081500d0, 0x654830, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:380 +0xbba
net/http.(*Client).Do(0x7e0040, 0xc2081500d0, 0xa, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:175 +0x9f
github.com/hashicorp/go-checkpoint.Check(0xc208158000, 0x0, 0x0, 0x0)
	/Users/bmizerany/src/github.com/hashicorp/go-checkpoint/checkpoint.go:139 +0xab0
main.runCheckpoint(0xc2080fa150)
	/Users/bmizerany/src/github.com/mitchellh/packer/checkpoint.go:51 +0x459
created by main.wrappedMain
	/Users/bmizerany/src/github.com/mitchellh/packer/main.go:120 +0x7d3

goroutine 10 [semacquire]:
sync.runtime_Syncsemacquire(0xc2080b0340)
	/usr/local/go/src/runtime/sema.go:237 +0x204
sync.(*Cond).Wait(0xc2080b0330)
	/usr/local/go/src/sync/cond.go:62 +0x9e
io.(*pipe).read(0xc2080b0300, 0xc20813d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:52 +0x304
io.(*PipeReader).Read(0xc20802a128, 0xc20813d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:134 +0x57
bufio.(*Scanner).Scan(0xc208092580, 0x0)
	/usr/local/go/src/bufio/scan.go:180 +0x873
github.com/mitchellh/packer/command.(*Meta).FlagSet.func1(0xc208092580, 0xc208015270)
	/Users/bmizerany/src/github.com/mitchellh/packer/command/meta.go:134 +0x28
created by github.com/mitchellh/packer/command.(*Meta).FlagSet
	/Users/bmizerany/src/github.com/mitchellh/packer/command/meta.go:137 +0x572

goroutine 18 [select]:
net.lookupIPDeadline(0xc208156080, 0x1c, 0xeccf705bb, 0x2031c610, 0x7e0240, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:93 +0x6a9
net.internetAddrList(0x553a00, 0x3, 0xc208156080, 0x20, 0xeccf705bb, 0x2031c610, 0x7e0240, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:252 +0x6f1
net.resolveAddrList(0x544640, 0x4, 0x553a00, 0x3, 0xc208156080, 0x20, 0xeccf705bb, 0x2031c610, 0x7e0240, 0x0, ...)
	/usr/local/go/src/net/dial.go:114 +0x469
net.(*Dialer).Dial(0xc208012400, 0x553a00, 0x3, 0xc208156080, 0x20, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:162 +0xe9
net.(*Dialer).Dial-fm(0x553a00, 0x3, 0xc208156080, 0x20, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:38 +0x71
net/http.(*Transport).dial(0xc208074090, 0x553a00, 0x3, 0xc208156080, 0x20, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:499 +0x7c
net/http.(*Transport).dialConn(0xc208074090, 0x0, 0xc20815c1c0, 0x5, 0xc208156080, 0x20, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:588 +0x1b56
net/http.(*Transport).getConn.func4(0xc208074090, 0x0, 0xc20815c1c0, 0x5, 0xc208156080, 0x20, 0xc208154060)
	/usr/local/go/src/net/http/transport.go:544 +0x69
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:546 +0x243

goroutine 35 [syscall, locked to thread]:
net._C2func_getaddrinfo(0xc00000, 0x0, 0xc208190548, 0xc208190470, 0x0, 0x0, 0x0)
	??:0 +0x4a
net.cgoLookupIPCNAME(0xc208156080, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x654700)
	/usr/local/go/src/net/cgo_unix.go:111 +0x1aa
net.cgoLookupIP(0xc208156080, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/cgo_unix.go:163 +0x59
net.lookupIP(0xc208156080, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup_unix.go:67 +0x97
net.glob.func15(0x654750, 0xc208156080, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/hook.go:8 +0x54
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:90 +0x74
internal/singleflight.(*Group).doCall(0x7df620, 0xc208172240, 0xc208156080, 0x1c, 0xc208174040)
	/usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2f
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:86 +0x454
```

**Comment by mitchellh** [comment]
Oops, certainly an oversight. Hard to write a unit test for that one since the newly added (this week) semantic checks won't cause anything that I know of to fail this at the moment. But added a return there.

**Comment by bmizerany** [comment]
Awesome.
