### ISSUE TITLE
Race conditions in winrm sometimes cause builds to hang / timeout in Travis

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#2312]
The Travis build periodically gets stuck because of a race condition that *I think* is located in the winrm test suite. The go 1.5 race detector is a bit more sophisticated (`go test -race ./...`) than 1.4. I've included a log here:

https://gist.github.com/cbednarski/61b78bdf857563a1e106

**Comment by cbednarski** [comment]
I spent a bit of time looking at this, but I'm going to defer this until go 1.5 is released. I want to make sure the 1.5 race detector is mature and available to upstreams before I dig into this more.

**Comment by cbednarski** [comment]
Looks like this is a panic in go 1.5:

```
panic: test timed out after 15s

goroutine 99 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:703 +0x132
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x4deaf0, 0x61e260, 0xe, 0xe, 0x0)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc8200dbed8, 0x1dc103af)
	/usr/local/go/src/testing/testing.go:494 +0x70
main.main()
	github.com/mitchellh/packer/provisioner/windows-restart/_test/_testmain.go:80 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 88 [chan receive]:
github.com/mitchellh/packer/provisioner/windows-restart.TestProvision_Cancel(0xc82019c120)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/provisioner/windows-restart/provisioner_test.go:351 +0x3ba
testing.tRunner(0xc82019c120, 0x61e398)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 89 [select]:
github.com/mitchellh/packer/provisioner/windows-restart.glob.func1(0xc8201a81c0, 0x0, 0x0)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/provisioner/windows-restart/provisioner.go:119 +0x5b2
github.com/mitchellh/packer/provisioner/windows-restart.(*Provisioner).Provision(0xc8201a81c0, 0xaa4bc8, 0xc820138780, 0xaa4c10, 0xc8201941a0, 0x0, 0x0)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/provisioner/windows-restart/provisioner.go:97 +0x352
github.com/mitchellh/packer/provisioner/windows-restart.TestProvision_Cancel.func2(0xc82018eb70, 0xc8201a81c0, 0xc820138780, 0xc8201941a0, 0xc82019acc0)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/provisioner/windows-restart/provisioner_test.go:344 +0xa5
created by github.com/mitchellh/packer/provisioner/windows-restart.TestProvision_Cancel
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/provisioner/windows-restart/provisioner_test.go:346 +0x375

goroutine 74 [chan receive]:
github.com/mitchellh/packer/provisioner/windows-restart.TestProvision_waitForRestartTimeout.func1(0xc820154380, 0x0, 0x0)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/provisioner/windows-restart/provisioner_test.go:201 +0x54
github.com/mitchellh/packer/provisioner/windows-restart.glob.func1.1(0xc82013af20, 0xc820154380, 0xc820141880)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/provisioner/windows-restart/provisioner.go:109 +0x56
created by github.com/mitchellh/packer/provisioner/windows-restart.glob.func1
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/provisioner/windows-restart/provisioner.go:111 +0x10d

goroutine 55 [chan receive]:
github.com/mitchellh/packer/provisioner/windows-restart.TestProvision_Cancel.func1(0xc8201a81c0, 0x0, 0x0)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/provisioner/windows-restart/provisioner_test.go:336 +0x54
github.com/mitchellh/packer/provisioner/windows-restart.glob.func1.1(0xc820174350, 0xc8201a81c0, 0xc82017e770)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/provisioner/windows-restart/provisioner.go:109 +0x56
created by github.com/mitchellh/packer/provisioner/windows-restart.glob.func1
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/provisioner/windows-restart/provisioner.go:111 +0x10d
FAIL	github.com/mitchellh/packer/provisioner/windows-restart	15.030s
ok  	github.com/mitchellh/packer/provisioner/windows-shell	0.178s
ok  	github.com/mitchellh/packer/template	0.025s
ok  	github.com/mitchellh/packer/template/interpolate	0.009s
make: *** [test] Error 2
```

**Comment by cbednarski** [comment]
@markpeek I think you fixed this already.. just want to confirm before closing.

**Comment by markpeek** [comment]
@cbednarski In general, yes, I fixed these issues with race conditions. The original issue here was addressed with a change pushed back into [winrm](https://github.com/masterzen/winrm) and the last one was probably fixed with the race fixes I committed to master.

**Comment by cbednarski** [comment]
Great, thanks for following up! :)
