### ISSUE TITLE
`packer validate` crashes on json syntax error

### ISSUE THREAD

**Issue by jarl-dk** [mitchellh/packer#2778]
I ran into a packer crash. terminal shows
```
$ packer validate -var-file=./centos71-docker-vars.json -only=virtualbox-iso ./centos71-docker.json
invalid value "./centos71-docker-vars.json" for flag -var-file: Error reading variables in './centos71-docker-vars.json': invalid character '}' looking for beginning of object key string
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x5b pc=0x580a40]

goroutine 10 [running]:
net/url.QueryEscape(0x956258, 0x4, 0x956258, 0x4)
        /usr/local/go/src/net/url/url.go:191
net/url.Values.Encode(0xc82012a600, 0x0, 0x0)


        /usr/local/go/src/net/url/url.go:744 +0x2fd
github.com/hashicorp/go-checkpoint.Check(0xc820044f28, 0x0, 0x0, 0x0)
        /Users/cbednarski/code/golang/src/github.com/hashicorp/go-checkpoint/checkpoint.go:130 +0x8ff
main.runCheckpoint(0xc820017ec0)
        /Users/cbednarski/code/golang/src/github.com/mitchellh/packer/checkpoint.go:51 +0x41a
created by main.wrappedMain
        /Users/cbednarski/code/golang/src/github.com/mitchellh/packer/main.go:121 +0x7b1

goroutine 1 [runnable]:
sync.runtime_Syncsemacquire(0xc8200ca378)
        /usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc8200ca368)
        /usr/local/go/src/sync/cond.go:62 +0x9b
io.(*pipe).write(0xc8200ca300, 0xc8200a0b40, 0xbb, 0x140, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:94 +0x23a
io.(*PipeWriter).Write(0xc8200300f0, 0xc8200a0b40, 0xbb, 0x140, 0x101, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:161 +0x50
fmt.Fprintln(0x7fbbdc182088, 0xc8200300f0, 0xc8200c5308, 0x1, 0x1, 0x7fbbdc17d028, 0x0, 0x0)
        /usr/local/go/src/fmt/print.go:255 +0xa5
flag.(*FlagSet).failf(0xc820014900, 0x9e17a0, 0x21, 0xc8200c54e8, 0x3, 0x3, 0x0, 0x0)
        /usr/local/go/src/flag/flag.go:798 +0x19d
flag.(*FlagSet).parseOne(0xc820014900, 0x9adf40, 0x0, 0x0)
        /usr/local/go/src/flag/flag.go:882 +0xff5
flag.(*FlagSet).Parse(0xc820014900, 0xc82000a250, 0x3, 0x3, 0x0, 0x0)
        /usr/local/go/src/flag/flag.go:900 +0x6e
github.com/mitchellh/packer/command.(*ValidateCommand).Run(0xc8200c7dc0, 0xc82000a250, 0x3, 0x3, 0xc8200d6cd8)
        /Users/cbednarski/code/golang/src/github.com/mitchellh/packer/command/validate.go:21 +0x1a3
github.com/mitchellh/cli.(*CLI).Run(0xc8200fdb80, 0xc8200fdb80, 0x0, 0x0)
        /Users/cbednarski/code/golang/src/github.com/mitchellh/cli/cli.go:112 +0x655
main.wrappedMain(0x0)
        /Users/cbednarski/code/golang/src/github.com/mitchellh/packer/main.go:187 +0x139f
main.realMain(0x0)
        /Users/cbednarski/code/golang/src/github.com/mitchellh/packer/main.go:91 +0xa88
main.main()
        /Users/cbednarski/code/golang/src/github.com/mitchellh/packer/main.go:26 +0x18

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc820144000, 0x8000, 0x28004369d1, 0x19, 0x1)
        /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x0, 0xc820144000, 0x8000, 0x8000, 0x7fbbdc13d148, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0x0, 0xc820144000, 0x8000, 0x8000, 0xc820144000, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0xc820030008, 0xc820144000, 0x8000, 0x8000, 0x88caa0, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:211 +0x53
os.(*File).Read(0xc820030008, 0xc820144000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
        /usr/local/go/src/os/file.go:95 +0x8a
io.copyBuffer(0x7fbbdc1811c0, 0xc8200300b0, 0x7fbbdc181298, 0xc820030008, 0xc820144000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:381 +0x247
io.Copy(0x7fbbdc1811c0, 0xc8200300b0, 0x7fbbdc181298, 0xc820030008, 0x95b850, 0x0, 0x0)
        /usr/local/go/src/io/io.go:351 +0x64
main.setupStdin.func1(0xc8200300b0, 0xc820030008)
        /Users/cbednarski/code/golang/src/github.com/mitchellh/packer/stdin.go:23 +0xb4
created by main.setupStdin
        /Users/cbednarski/code/golang/src/github.com/mitchellh/packer/stdin.go:24 +0x76

goroutine 8 [select, locked to thread]:
runtime.gopark(0xa3ca90, 0xc82002ef28, 0x95a538, 0x6, 0x18, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002ef28, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002ef28)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 9 [chan receive]:
main.setupStdin.func2(0xc820014540, 0xc8200300b0)
        /Users/cbednarski/code/golang/src/github.com/mitchellh/packer/stdin.go:34 +0x93
created by main.setupStdin
        /Users/cbednarski/code/golang/src/github.com/mitchellh/packer/stdin.go:36 +0x13c

goroutine 11 [semacquire]:
sync.runtime_Syncsemacquire(0xc8200ca340)
        /usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc8200ca330)
        /usr/local/go/src/sync/cond.go:62 +0x9b
io.(*pipe).read(0xc8200ca300, 0xc8201740bb, 0xf45, 0xf45, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:52 +0x2d2
io.(*PipeReader).Read(0xc8200300e8, 0xc8201740bb, 0xf45, 0xf45, 0xc8200a80b0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:134 +0x50
bufio.(*Scanner).Scan(0xc82009cd00, 0xc8200ca480)
        /usr/local/go/src/bufio/scan.go:180 +0x877
github.com/mitchellh/packer/command.(*Meta).FlagSet.func1(0xc82009cd00, 0xc8200c7dc0)
        /Users/cbednarski/code/golang/src/github.com/mitchellh/packer/command/meta.go:131 +0x25
created by github.com/mitchellh/packer/command.(*Meta).FlagSet
        /Users/cbednarski/code/golang/src/github.com/mitchellh/packer/command/meta.go:134 +0x56e



!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/mitchellh/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

logfile (`crash.log`) contains:
```
2015/09/26 07:11:00 [INFO] Packer version: 0.8.6  f8f7b7a34c1be06058f5aca23a51247db12cdbc5+CHANGES
2015/09/26 07:11:00 Packer Target OS/Arch: linux amd64
2015/09/26 07:11:00 Built with Go Version: go1.5
2015/09/26 07:11:00 [DEBUG] Discovered plugin: amazon-chroot = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-amazon-chroot
2015/09/26 07:11:00 [DEBUG] Discovered plugin: amazon-ebs = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-amazon-ebs
2015/09/26 07:11:00 [DEBUG] Discovered plugin: amazon-instance = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-amazon-instance
2015/09/26 07:11:00 [DEBUG] Discovered plugin: digitalocean = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-digitalocean
2015/09/26 07:11:00 [DEBUG] Discovered plugin: docker = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-docker
2015/09/26 07:11:00 [DEBUG] Discovered plugin: file = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-file
2015/09/26 07:11:00 [DEBUG] Discovered plugin: googlecompute = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-googlecompute
2015/09/26 07:11:00 [DEBUG] Discovered plugin: null = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-null
2015/09/26 07:11:00 [DEBUG] Discovered plugin: openstack = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-openstack
2015/09/26 07:11:00 [DEBUG] Discovered plugin: parallels-iso = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-parallels-iso
2015/09/26 07:11:00 [DEBUG] Discovered plugin: parallels-pvm = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-parallels-pvm
2015/09/26 07:11:00 [DEBUG] Discovered plugin: qemu = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-qemu
2015/09/26 07:11:00 [DEBUG] Discovered plugin: virtualbox-iso = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-virtualbox-iso
2015/09/26 07:11:00 [DEBUG] Discovered plugin: virtualbox-ovf = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-virtualbox-ovf
2015/09/26 07:11:00 [DEBUG] Discovered plugin: vmware-iso = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-vmware-iso
2015/09/26 07:11:00 [DEBUG] Discovered plugin: vmware-vmx = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-vmware-vmx
2015/09/26 07:11:00 [DEBUG] Discovered plugin: artifice = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-artifice
2015/09/26 07:11:00 [DEBUG] Discovered plugin: atlas = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-atlas
2015/09/26 07:11:00 [DEBUG] Discovered plugin: compress = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-compress
2015/09/26 07:11:00 [DEBUG] Discovered plugin: docker-import = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-docker-import
2015/09/26 07:11:00 [DEBUG] Discovered plugin: docker-push = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-docker-push
2015/09/26 07:11:00 [DEBUG] Discovered plugin: docker-save = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-docker-save
2015/09/26 07:11:00 [DEBUG] Discovered plugin: docker-tag = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-docker-tag
2015/09/26 07:11:00 [DEBUG] Discovered plugin: vagrant = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-vagrant
2015/09/26 07:11:00 [DEBUG] Discovered plugin: vagrant-cloud = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-vagrant-cloud
2015/09/26 07:11:00 [DEBUG] Discovered plugin: vsphere = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-vsphere
2015/09/26 07:11:00 [DEBUG] Discovered plugin: ansible-local = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-ansible-local
2015/09/26 07:11:00 [DEBUG] Discovered plugin: chef-client = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-chef-client
2015/09/26 07:11:00 [DEBUG] Discovered plugin: chef-solo = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-chef-solo
2015/09/26 07:11:00 [DEBUG] Discovered plugin: file = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-file
2015/09/26 07:11:00 [DEBUG] Discovered plugin: powershell = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-powershell
2015/09/26 07:11:00 [DEBUG] Discovered plugin: puppet-masterless = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-puppet-masterless
2015/09/26 07:11:00 [DEBUG] Discovered plugin: puppet-server = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-puppet-server
2015/09/26 07:11:00 [DEBUG] Discovered plugin: salt-masterless = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-salt-masterless
2015/09/26 07:11:00 [DEBUG] Discovered plugin: shell = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-shell
2015/09/26 07:11:00 [DEBUG] Discovered plugin: shell-local = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-shell-local
2015/09/26 07:11:00 [DEBUG] Discovered plugin: windows-restart = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-windows-restart
2015/09/26 07:11:00 [DEBUG] Discovered plugin: windows-shell = /home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-windows-shell
2015/09/26 07:11:00 Detected home directory from env var: /home/jarl
2015/09/26 07:11:00 Detected home directory from env var: /home/jarl
2015/09/26 07:11:00 Attempting to open config file: /home/jarl/.packerconfig
2015/09/26 07:11:00 [WARN] Config file doesn't exist: /home/jarl/.packerconfig
2015/09/26 07:11:00 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[parallels-pvm:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-parallels-pvm virtualbox-iso:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-virtualbox-iso amazon-chroot:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-amazon-chroot digitalocean:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-digitalocean docker:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-docker null:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-null openstack:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-openstack amazon-ebs:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-amazon-ebs file:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-file qemu:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-qemu virtualbox-ovf:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-virtualbox-ovf vmware-iso:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-vmware-iso amazon-instance:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-amazon-instance googlecompute:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-googlecompute parallels-iso:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-parallels-iso vmware-vmx:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-builder-vmware-vmx] PostProcessors:map[atlas:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-atlas docker-import:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-docker-import docker-tag:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-docker-tag vsphere:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-vsphere artifice:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-artifice compress:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-compress docker-push:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-docker-push docker-save:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-docker-save vagrant:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-vagrant vagrant-cloud:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-post-processor-vagrant-cloud] Provisioners:map[puppet-masterless:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-puppet-masterless salt-masterless:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-salt-masterless ansible-local:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-ansible-local chef-solo:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-chef-solo powershell:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-powershell shell:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-shell shell-local:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-shell-local windows-restart:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-windows-restart windows-shell:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-windows-shell chef-client:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-chef-client file:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-file puppet-server:/home/jarl/opt/packer_0.8.6_linux_amd64/packer-provisioner-puppet-server]}
2015/09/26 07:11:00 Setting cache directory: /home/jarl/projects/skat/packer/packer_cache
2015/09/26 07:11:00 Detected home directory from env var: /home/jarl
2015/09/26 07:11:00 ui error: invalid value "./centos71-docker-vars.json" for flag -var-file: Error reading variables in './centos71-docker-vars.json': invalid character '}' looking for beginning of object key string
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x5b pc=0x580a40]

goroutine 10 [running]:
net/url.QueryEscape(0x956258, 0x4, 0x956258, 0x4)
	/usr/local/go/src/net/url/url.go:191
net/url.Values.Encode(0xc82012a600, 0x0, 0x0)
	/usr/local/go/src/net/url/url.go:744 +0x2fd
github.com/hashicorp/go-checkpoint.Check(0xc820044f28, 0x0, 0x0, 0x0)
	/Users/cbednarski/code/golang/src/github.com/hashicorp/go-checkpoint/checkpoint.go:130 +0x8ff
main.runCheckpoint(0xc820017ec0)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/checkpoint.go:51 +0x41a
created by main.wrappedMain
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/main.go:121 +0x7b1

goroutine 1 [runnable]:
sync.runtime_Syncsemacquire(0xc8200ca378)
	/usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc8200ca368)
	/usr/local/go/src/sync/cond.go:62 +0x9b
io.(*pipe).write(0xc8200ca300, 0xc8200a0b40, 0xbb, 0x140, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:94 +0x23a
io.(*PipeWriter).Write(0xc8200300f0, 0xc8200a0b40, 0xbb, 0x140, 0x101, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:161 +0x50
fmt.Fprintln(0x7fbbdc182088, 0xc8200300f0, 0xc8200c5308, 0x1, 0x1, 0x7fbbdc17d028, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:255 +0xa5
flag.(*FlagSet).failf(0xc820014900, 0x9e17a0, 0x21, 0xc8200c54e8, 0x3, 0x3, 0x0, 0x0)
	/usr/local/go/src/flag/flag.go:798 +0x19d
flag.(*FlagSet).parseOne(0xc820014900, 0x9adf40, 0x0, 0x0)
	/usr/local/go/src/flag/flag.go:882 +0xff5
flag.(*FlagSet).Parse(0xc820014900, 0xc82000a250, 0x3, 0x3, 0x0, 0x0)
	/usr/local/go/src/flag/flag.go:900 +0x6e
github.com/mitchellh/packer/command.(*ValidateCommand).Run(0xc8200c7dc0, 0xc82000a250, 0x3, 0x3, 0xc8200d6cd8)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/command/validate.go:21 +0x1a3
github.com/mitchellh/cli.(*CLI).Run(0xc8200fdb80, 0xc8200fdb80, 0x0, 0x0)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/cli/cli.go:112 +0x655
main.wrappedMain(0x0)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/main.go:187 +0x139f
main.realMain(0x0)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/main.go:91 +0xa88
main.main()
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/main.go:26 +0x18

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc820144000, 0x8000, 0x28004369d1, 0x19, 0x1)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x0, 0xc820144000, 0x8000, 0x8000, 0x7fbbdc13d148, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0x0, 0xc820144000, 0x8000, 0x8000, 0xc820144000, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0xc820030008, 0xc820144000, 0x8000, 0x8000, 0x88caa0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:211 +0x53
os.(*File).Read(0xc820030008, 0xc820144000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x8a
io.copyBuffer(0x7fbbdc1811c0, 0xc8200300b0, 0x7fbbdc181298, 0xc820030008, 0xc820144000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:381 +0x247
io.Copy(0x7fbbdc1811c0, 0xc8200300b0, 0x7fbbdc181298, 0xc820030008, 0x95b850, 0x0, 0x0)
	/usr/local/go/src/io/io.go:351 +0x64
main.setupStdin.func1(0xc8200300b0, 0xc820030008)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/stdin.go:23 +0xb4
created by main.setupStdin
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/stdin.go:24 +0x76

goroutine 8 [select, locked to thread]:
runtime.gopark(0xa3ca90, 0xc82002ef28, 0x95a538, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002ef28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002ef28)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 9 [chan receive]:
main.setupStdin.func2(0xc820014540, 0xc8200300b0)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/stdin.go:34 +0x93
created by main.setupStdin
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/stdin.go:36 +0x13c

goroutine 11 [semacquire]:
sync.runtime_Syncsemacquire(0xc8200ca340)
	/usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc8200ca330)
	/usr/local/go/src/sync/cond.go:62 +0x9b
io.(*pipe).read(0xc8200ca300, 0xc8201740bb, 0xf45, 0xf45, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:52 +0x2d2
io.(*PipeReader).Read(0xc8200300e8, 0xc8201740bb, 0xf45, 0xf45, 0xc8200a80b0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:134 +0x50
bufio.(*Scanner).Scan(0xc82009cd00, 0xc8200ca480)
	/usr/local/go/src/bufio/scan.go:180 +0x877
github.com/mitchellh/packer/command.(*Meta).FlagSet.func1(0xc82009cd00, 0xc8200c7dc0)
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/command/meta.go:131 +0x25
created by github.com/mitchellh/packer/command.(*Meta).FlagSet
	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/command/meta.go:134 +0x56e
```

The offending file `centos71-docker-vars.json` (which contains a syntax error) contains:
```
{
  "iso_checksum": "7c1e34e95c991175290d704dbdcc6531774cbecb",
  "iso_url": "http://mirror2.hs-esslingen.de/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1503-01.iso",
}
```

**Comment by jarl-dk** [comment]
I tried out the bleeding edge version (master, https://github.com/mitchellh/packer/commit/f2013a9c0cb2100cbd99cfce5cbc504e979be386) of packer. There the issue was fixed.
