### ISSUE TITLE
Crash with packer on vmware

### ISSUE THREAD

**Issue by xrow** [mitchellh/packer#2827]
Packer crashed while running wiht vmware prodiver. It was not crashing when I used my virtualbox provider. Please let know know what additional Information you might need. I try to upgrade to latest version and see if the problem exists there too.

This is a contents of the crash log.

```
2015/10/13 10:34:16 [INFO] Packer version: 0.8.0  88e689faa22605759ee91c22bad9a5f463fcf78a+CHANGES
2015/10/13 10:34:16 Packer Target OS/Arch: linux amd64
2015/10/13 10:34:16 Built with Go Version: go1.4.2
2015/10/13 10:34:16 [DEBUG] Discovered plugin: amazon-chroot = /opt/packer/packer-builder-amazon-chroot
2015/10/13 10:34:16 [DEBUG] Discovered plugin: amazon-ebs = /opt/packer/packer-builder-amazon-ebs
2015/10/13 10:34:16 [DEBUG] Discovered plugin: amazon-instance = /opt/packer/packer-builder-amazon-instance
2015/10/13 10:34:16 [DEBUG] Discovered plugin: digitalocean = /opt/packer/packer-builder-digitalocean
2015/10/13 10:34:16 [DEBUG] Discovered plugin: docker = /opt/packer/packer-builder-docker
2015/10/13 10:34:16 [DEBUG] Discovered plugin: file = /opt/packer/packer-builder-file
2015/10/13 10:34:16 [DEBUG] Discovered plugin: googlecompute = /opt/packer/packer-builder-googlecompute
2015/10/13 10:34:16 [DEBUG] Discovered plugin: null = /opt/packer/packer-builder-null
2015/10/13 10:34:16 [DEBUG] Discovered plugin: openstack = /opt/packer/packer-builder-openstack
2015/10/13 10:34:16 [DEBUG] Discovered plugin: parallels-iso = /opt/packer/packer-builder-parallels-iso
2015/10/13 10:34:16 [DEBUG] Discovered plugin: parallels-pvm = /opt/packer/packer-builder-parallels-pvm
2015/10/13 10:34:16 [DEBUG] Discovered plugin: qemu = /opt/packer/packer-builder-qemu
2015/10/13 10:34:16 [DEBUG] Discovered plugin: virtualbox-iso = /opt/packer/packer-builder-virtualbox-iso
2015/10/13 10:34:16 [DEBUG] Discovered plugin: virtualbox-ovf = /opt/packer/packer-builder-virtualbox-ovf
2015/10/13 10:34:16 [DEBUG] Discovered plugin: vmware-iso = /opt/packer/packer-builder-vmware-iso
2015/10/13 10:34:16 [DEBUG] Discovered plugin: vmware-vmx = /opt/packer/packer-builder-vmware-vmx
2015/10/13 10:34:16 [DEBUG] Discovered plugin: atlas = /opt/packer/packer-post-processor-atlas
2015/10/13 10:34:16 [DEBUG] Discovered plugin: compress = /opt/packer/packer-post-processor-compress
2015/10/13 10:34:16 [DEBUG] Discovered plugin: docker-import = /opt/packer/packer-post-processor-docker-import
2015/10/13 10:34:16 [DEBUG] Discovered plugin: docker-push = /opt/packer/packer-post-processor-docker-push
2015/10/13 10:34:16 [DEBUG] Discovered plugin: docker-save = /opt/packer/packer-post-processor-docker-save
2015/10/13 10:34:16 [DEBUG] Discovered plugin: docker-tag = /opt/packer/packer-post-processor-docker-tag
2015/10/13 10:34:16 [DEBUG] Discovered plugin: vagrant = /opt/packer/packer-post-processor-vagrant
2015/10/13 10:34:16 [DEBUG] Discovered plugin: vagrant-cloud = /opt/packer/packer-post-processor-vagrant-cloud
2015/10/13 10:34:16 [DEBUG] Discovered plugin: vsphere = /opt/packer/packer-post-processor-vsphere
2015/10/13 10:34:16 [DEBUG] Discovered plugin: ansible-local = /opt/packer/packer-provisioner-ansible-local
2015/10/13 10:34:16 [DEBUG] Discovered plugin: chef-client = /opt/packer/packer-provisioner-chef-client
2015/10/13 10:34:16 [DEBUG] Discovered plugin: chef-solo = /opt/packer/packer-provisioner-chef-solo
2015/10/13 10:34:16 [DEBUG] Discovered plugin: file = /opt/packer/packer-provisioner-file
2015/10/13 10:34:16 [DEBUG] Discovered plugin: powershell = /opt/packer/packer-provisioner-powershell
2015/10/13 10:34:16 [DEBUG] Discovered plugin: puppet-masterless = /opt/packer/packer-provisioner-puppet-masterless
2015/10/13 10:34:16 [DEBUG] Discovered plugin: puppet-server = /opt/packer/packer-provisioner-puppet-server
2015/10/13 10:34:16 [DEBUG] Discovered plugin: salt-masterless = /opt/packer/packer-provisioner-salt-masterless
2015/10/13 10:34:16 [DEBUG] Discovered plugin: shell = /opt/packer/packer-provisioner-shell
2015/10/13 10:34:16 [DEBUG] Discovered plugin: shell-local = /opt/packer/packer-provisioner-shell-local
2015/10/13 10:34:16 [DEBUG] Discovered plugin: windows-restart = /opt/packer/packer-provisioner-windows-restart
2015/10/13 10:34:16 [DEBUG] Discovered plugin: windows-shell = /opt/packer/packer-provisioner-windows-shell
2015/10/13 10:34:16 Detected home directory from env var: /root
2015/10/13 10:34:16 Detected home directory from env var: /root
2015/10/13 10:34:16 Attempting to open config file: /root/.packerconfig
2015/10/13 10:34:16 [WARN] Config file doesn't exist: /root/.packerconfig
2015/10/13 10:34:16 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[googlecompute:/opt/packer/packer-builder-googlecompute openstack:/opt/packer/packer-builder-openstack parallels-iso:/opt/packer/packer-builder-parallels-iso parallels-pvm:/opt/packer/packer-builder-parallels-pvm amazon-chroot:/opt/packer/packer-builder-amazon-chroot amazon-instance:/opt/packer/packer-builder-amazon-instance digitalocean:/opt/packer/packer-builder-digitalocean file:/opt/packer/packer-builder-file vmware-vmx:/opt/packer/packer-builder-vmware-vmx amazon-ebs:/opt/packer/packer-builder-amazon-ebs null:/opt/packer/packer-builder-null vmware-iso:/opt/packer/packer-builder-vmware-iso docker:/opt/packer/packer-builder-docker qemu:/opt/packer/packer-builder-qemu virtualbox-iso:/opt/packer/packer-builder-virtualbox-iso virtualbox-ovf:/opt/packer/packer-builder-virtualbox-ovf] PostProcessors:map[docker-push:/opt/packer/packer-post-processor-docker-push docker-tag:/opt/packer/packer-post-processor-docker-tag vagrant:/opt/packer/packer-post-processor-vagrant vagrant-cloud:/opt/packer/packer-post-processor-vagrant-cloud vsphere:/opt/packer/packer-post-processor-vsphere atlas:/opt/packer/packer-post-processor-atlas docker-import:/opt/packer/packer-post-processor-docker-import docker-save:/opt/packer/packer-post-processor-docker-save compress:/opt/packer/packer-post-processor-compress] Provisioners:map[powershell:/opt/packer/packer-provisioner-powershell windows-restart:/opt/packer/packer-provisioner-windows-restart chef-solo:/opt/packer/packer-provisioner-chef-solo file:/opt/packer/packer-provisioner-file puppet-masterless:/opt/packer/packer-provisioner-puppet-masterless puppet-server:/opt/packer/packer-provisioner-puppet-server salt-masterless:/opt/packer/packer-provisioner-salt-masterless shell:/opt/packer/packer-provisioner-shell ansible-local:/opt/packer/packer-provisioner-ansible-local chef-client:/opt/packer/packer-provisioner-chef-client shell-local:/opt/packer/packer-provisioner-shell-local windows-shell:/opt/packer/packer-provisioner-windows-shell]}
2015/10/13 10:34:16 Setting cache directory: /root/packer/centos-7.1.1503-x86_64/packer_cache
2015/10/13 10:34:16 Detected home directory from env var: /root
2015/10/13 10:34:16 Loading builder: vmware-iso
2015/10/13 10:34:16 Creating plugin client for path: /opt/packer/packer-builder-vmware-iso
2015/10/13 10:34:16 Starting plugin: /opt/packer/packer-builder-vmware-iso []string{"/opt/packer/packer-builder-vmware-iso"}
2015/10/13 10:34:16 Waiting for RPC address for: /opt/packer/packer-builder-vmware-iso
2015/10/13 10:34:16 packer-builder-vmware-iso: 2015/10/13 10:34:16 Plugin minimum port: 10000
2015/10/13 10:34:16 packer-builder-vmware-iso: 2015/10/13 10:34:16 Plugin maximum port: 25000
2015/10/13 10:34:16 packer-builder-vmware-iso: 2015/10/13 10:34:16 Plugin address: unix /tmp/packer-plugin308079146
2015/10/13 10:34:16 packer-builder-vmware-iso: 2015/10/13 10:34:16 Waiting for connection...
2015/10/13 10:34:16 packer-builder-vmware-iso: 2015/10/13 10:34:16 Serving a plugin connection...
2015/10/13 10:34:16 Loading provisioner: shell
2015/10/13 10:34:16 Creating plugin client for path: /opt/packer/packer-provisioner-shell
2015/10/13 10:34:16 Starting plugin: /opt/packer/packer-provisioner-shell []string{"/opt/packer/packer-provisioner-shell"}
2015/10/13 10:34:16 Waiting for RPC address for: /opt/packer/packer-provisioner-shell
2015/10/13 10:34:16 packer-provisioner-shell: 2015/10/13 10:34:16 Plugin minimum port: 10000
2015/10/13 10:34:16 packer-provisioner-shell: 2015/10/13 10:34:16 Plugin maximum port: 25000
2015/10/13 10:34:16 packer-provisioner-shell: 2015/10/13 10:34:16 Plugin address: unix /tmp/packer-plugin684407230
2015/10/13 10:34:16 packer-provisioner-shell: 2015/10/13 10:34:16 Waiting for connection...
2015/10/13 10:34:16 packer-provisioner-shell: 2015/10/13 10:34:16 Serving a plugin connection...
2015/10/13 10:34:16 Loading provisioner: shell
2015/10/13 10:34:16 Creating plugin client for path: /opt/packer/packer-provisioner-shell
2015/10/13 10:34:16 Starting plugin: /opt/packer/packer-provisioner-shell []string{"/opt/packer/packer-provisioner-shell"}
2015/10/13 10:34:16 Waiting for RPC address for: /opt/packer/packer-provisioner-shell
2015/10/13 10:34:16 packer-provisioner-shell: 2015/10/13 10:34:16 Plugin minimum port: 10000
2015/10/13 10:34:16 packer-provisioner-shell: 2015/10/13 10:34:16 Plugin maximum port: 25000
2015/10/13 10:34:16 packer-provisioner-shell: 2015/10/13 10:34:16 Plugin address: unix /tmp/packer-plugin979066123
2015/10/13 10:34:16 packer-provisioner-shell: 2015/10/13 10:34:16 Waiting for connection...
2015/10/13 10:34:16 packer-provisioner-shell: 2015/10/13 10:34:16 Serving a plugin connection...
2015/10/13 10:34:16 Loading post-processor: compress
2015/10/13 10:34:16 Creating plugin client for path: /opt/packer/packer-post-processor-compress
2015/10/13 10:34:16 Starting plugin: /opt/packer/packer-post-processor-compress []string{"/opt/packer/packer-post-processor-compress"}
2015/10/13 10:34:16 Waiting for RPC address for: /opt/packer/packer-post-processor-compress
2015/10/13 10:34:16 packer-post-processor-compress: 2015/10/13 10:34:16 Plugin minimum port: 10000
2015/10/13 10:34:16 packer-post-processor-compress: 2015/10/13 10:34:16 Plugin maximum port: 25000
2015/10/13 10:34:16 packer-post-processor-compress: 2015/10/13 10:34:16 Plugin address: unix /tmp/packer-plugin665807080
2015/10/13 10:34:16 packer-post-processor-compress: 2015/10/13 10:34:16 Waiting for connection...
2015/10/13 10:34:16 packer-post-processor-compress: 2015/10/13 10:34:16 Serving a plugin connection...
2015/10/13 10:34:16 ui: vmware-iso output will be in this color.
2015/10/13 10:34:16 ui: 
2015/10/13 10:34:16 Build debug mode: false
2015/10/13 10:34:16 Force build: false
2015/10/13 10:34:16 Preparing build: vmware-iso
2015/10/13 10:34:16 packer-post-processor-compress: panic: runtime error: invalid memory address or nil pointer dereference
2015/10/13 10:34:16 packer-post-processor-compress: [signal 0xb code=0x1 addr=0x0 pc=0x446c79]
2015/10/13 10:34:16 packer-post-processor-compress: 
2015/10/13 10:34:16 packer-post-processor-compress: goroutine 18 [running]:
2015/10/13 10:34:16 packer-post-processor-compress: github.com/mitchellh/packer/post-processor/compress.(*PostProcessor).Configure(0xc208030090, 0xc2080f6200, 0x2, 0x2, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/post-processor/compress/post-processor.go:59 +0xd39
2015/10/13 10:34:16 packer-post-processor-compress: github.com/mitchellh/packer/packer/rpc.(*PostProcessorServer).Configure(0xc20801f0c0, 0xc2080f61a0, 0xc2080e8580, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/post_processor.go:71 +0x6f
2015/10/13 10:34:16 packer-post-processor-compress: reflect.Value.call(0x7be6a0, 0x7fbf00, 0x13, 0x87aeb0, 0x4, 0xc208057f28, 0x3, 0x3, 0x0, 0x0, ...)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/reflect/value.go:419 +0x10e5
2015/10/13 10:34:16 packer-post-processor-compress: reflect.Value.Call(0x7be6a0, 0x7fbf00, 0x13, 0xc208057f28, 0x3, 0x3, 0x0, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/reflect/value.go:296 +0xbc
2015/10/13 10:34:16 packer-post-processor-compress: net/rpc.(*service).call(0xc20803dc00, 0xc20803dbc0, 0xc2080e8018, 0xc2080aa480, 0xc2080f60a0, 0x71eba0, 0xc2080f61a0, 0x16, 0x71f8c0, 0xc2080e8580, ...)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/net/rpc/server.go:382 +0x1f7
2015/10/13 10:34:16 packer-post-processor-compress: created by net/rpc.(*Server).ServeCodec
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/net/rpc/server.go:476 +0x44a
2015/10/13 10:34:16 packer-post-processor-compress: 
2015/10/13 10:34:16 packer-post-processor-compress: goroutine 1 [select]:
2015/10/13 10:34:16 packer-post-processor-compress: github.com/hashicorp/yamux.(*Stream).Read(0xc2080363c0, 0xc2080fb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/stream.go:125 +0x3ab
2015/10/13 10:34:16 packer-post-processor-compress: bufio.(*Reader).fill(0xc2080f4060)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/bufio/bufio.go:97 +0x1ce
2015/10/13 10:34:16 packer-post-processor-compress: bufio.(*Reader).ReadByte(0xc2080f4060, 0x0, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/bufio/bufio.go:196 +0x86
2015/10/13 10:34:16 packer-post-processor-compress: github.com/hashicorp/go-msgpack/codec.(*ioDecReader).readn1(0xc2080f2060, 0xc2080f6080)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:90 +0x45
2015/10/13 10:34:16 packer-post-processor-compress: github.com/hashicorp/go-msgpack/codec.(*msgpackDecDriver).initReadNext(0xc2080f6080)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/msgpack.go:540 +0x48
2015/10/13 10:34:16 packer-post-processor-compress: github.com/hashicorp/go-msgpack/codec.(*Decoder).decode(0xc2080f40c0, 0x723ee0, 0xc2080f63a0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:635 +0x59
2015/10/13 10:34:16 packer-post-processor-compress: github.com/hashicorp/go-msgpack/codec.(*Decoder).Decode(0xc2080f40c0, 0x723ee0, 0xc2080f63a0, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/decode.go:630 +0x7f
2015/10/13 10:34:16 packer-post-processor-compress: github.com/hashicorp/go-msgpack/codec.(*rpcCodec).read(0xc2080e6100, 0x723ee0, 0xc2080f63a0, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/rpc.go:88 +0xd9
2015/10/13 10:34:16 packer-post-processor-compress: github.com/hashicorp/go-msgpack/codec.(*goRpcCodec).ReadRequestHeader(0xc2080e6100, 0xc2080f63a0, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/go-msgpack/codec/rpc.go:127 +0x61
2015/10/13 10:34:16 packer-post-processor-compress: net/rpc.(*Server).readRequestHeader(0xc20803dbc0, 0x7fc874f1dc20, 0xc2080e6100, 0x0, 0x0, 0xc2080f63a0, 0x0, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/net/rpc/server.go:575 +0x97
2015/10/13 10:34:16 packer-post-processor-compress: net/rpc.(*Server).readRequest(0xc20803dbc0, 0x7fc874f1dc20, 0xc2080e6100, 0xc2080aa480, 0xc2080f60a0, 0x71eba0, 0x0, 0x0, 0x0, 0x0, ...)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/net/rpc/server.go:542 +0xa2
2015/10/13 10:34:16 packer-post-processor-compress: net/rpc.(*Server).ServeCodec(0xc20803dbc0, 0x7fc874f1dc20, 0xc2080e6100)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/net/rpc/server.go:461 +0x6d
2015/10/13 10:34:16 packer-post-processor-compress: github.com/mitchellh/packer/packer/rpc.(*Server).Serve(0xc20801f080)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/server.go:141 +0x26f
2015/10/13 10:34:16 packer-post-processor-compress: main.main()
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/plugin/post-processor-compress/main.go:14 +0xc7
2015/10/13 10:34:16 packer-post-processor-compress: 
2015/10/13 10:34:16 packer-post-processor-compress: goroutine 5 [syscall]:
2015/10/13 10:34:16 packer-post-processor-compress: os/signal.loop()
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/os/signal/signal_unix.go:21 +0x1f
2015/10/13 10:34:16 packer-post-processor-compress: created by os/signal.init·1
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/os/signal/signal_unix.go:27 +0x35
2015/10/13 10:34:16 packer-post-processor-compress: 
2015/10/13 10:34:16 packer-post-processor-compress: goroutine 7 [chan receive]:
2015/10/13 10:34:16 packer-post-processor-compress: github.com/mitchellh/packer/packer/plugin.func·017()
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/plugin/server.go:92 +0x69
2015/10/13 10:34:16 packer-post-processor-compress: created by github.com/mitchellh/packer/packer/plugin.Server
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/plugin/server.go:96 +0xcca
2015/10/13 10:34:16 packer-post-processor-compress: 
2015/10/13 10:34:16 packer-post-processor-compress: goroutine 8 [IO wait]:
2015/10/13 10:34:16 packer-post-processor-compress: net.(*pollDesc).Wait(0xc208010220, 0x72, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/net/fd_poll_runtime.go:84 +0x47
2015/10/13 10:34:16 packer-post-processor-compress: net.(*pollDesc).WaitRead(0xc208010220, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/net/fd_poll_runtime.go:89 +0x43
2015/10/13 10:34:16 packer-post-processor-compress: net.(*netFD).Read(0xc2080101c0, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x7fc874f1bfc0, 0xc2080fe010)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/net/fd_unix.go:242 +0x40f
2015/10/13 10:34:16 packer-post-processor-compress: net.(*conn).Read(0xc208030080, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/net/net.go:121 +0xdc
2015/10/13 10:34:16 packer-post-processor-compress: bufio.(*Reader).fill(0xc208034360)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/bufio/bufio.go:97 +0x1ce
2015/10/13 10:34:16 packer-post-processor-compress: bufio.(*Reader).Read(0xc208034360, 0xc20800b1c0, 0xc, 0xc, 0xc2080fe000, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/bufio/bufio.go:174 +0x26c
2015/10/13 10:34:16 packer-post-processor-compress: io.ReadAtLeast(0x7fc874f1d700, 0xc208034360, 0xc20800b1c0, 0xc, 0xc, 0xc, 0x0, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/io/io.go:298 +0xf1
2015/10/13 10:34:16 packer-post-processor-compress: io.ReadFull(0x7fc874f1d700, 0xc208034360, 0xc20800b1c0, 0xc, 0xc, 0xc, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/3rdparty/go/src/io/io.go:316 +0x6d
2015/10/13 10:34:16 packer-post-processor-compress: github.com/hashicorp/yamux.(*Session).recvLoop(0xc20807d970, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:373 +0x10d
2015/10/13 10:34:16 packer-post-processor-compress: github.com/hashicorp/yamux.(*Session).recv(0xc20807d970)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:361 +0x28
2015/10/13 10:34:16 packer-post-processor-compress: created by github.com/hashicorp/yamux.newSession
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:104 +0x499
2015/10/13 10:34:16 packer-post-processor-compress: 
2015/10/13 10:34:16 packer-post-processor-compress: goroutine 9 [select]:
2015/10/13 10:34:16 packer-post-processor-compress: github.com/hashicorp/yamux.(*Session).send(0xc20807d970)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:323 +0x554
2015/10/13 10:34:16 packer-post-processor-compress: created by github.com/hashicorp/yamux.newSession
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:105 +0x4b3
2015/10/13 10:34:16 packer-post-processor-compress: 
2015/10/13 10:34:16 packer-post-processor-compress: goroutine 10 [select]:
2015/10/13 10:34:16 packer-post-processor-compress: github.com/hashicorp/yamux.(*Session).keepalive(0xc20807d970)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:279 +0x106
2015/10/13 10:34:16 packer-post-processor-compress: created by github.com/hashicorp/yamux.newSession
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:107 +0x4de
2015/10/13 10:34:16 packer-post-processor-compress: 
2015/10/13 10:34:16 packer-post-processor-compress: goroutine 11 [select]:
2015/10/13 10:34:16 packer-post-processor-compress: github.com/hashicorp/yamux.(*Session).AcceptStream(0xc20807d970, 0xc200000000, 0x0, 0x0)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/hashicorp/yamux/session.go:183 +0x1a8
2015/10/13 10:34:16 packer-post-processor-compress: github.com/mitchellh/packer/packer/rpc.(*muxBroker).Run(0xc20801f060)
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/mux_broker.go:126 +0x37
2015/10/13 10:34:16 packer-post-processor-compress: created by github.com/mitchellh/packer/packer/rpc.NewServer
2015/10/13 10:34:16 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/packer/rpc/server.go:42 +0x7a
2015/10/13 10:34:16 /opt/packer/packer-post-processor-compress: plugin process exited
2015/10/13 10:34:16 ui error: unexpected EOF
2015/10/13 10:34:16 waiting for all plugin processes to complete...
2015/10/13 10:34:16 /opt/packer/packer-provisioner-shell: plugin process exited
2015/10/13 10:34:16 /opt/packer/packer-builder-vmware-iso: plugin process exited
2015/10/13 10:34:16 /opt/packer/packer-provisioner-shell: plugin process exited
```
This is the template
```
{
  "variables": {
      "vm_name": "centos-7.1.1503-x86_64",
      "iso_checksum": "d07ab3e615c66a8b2e9a50f4852e6a77",
      "iso_url": "http://ftp.hosteurope.de/mirror/centos.org/7/isos/x86_64/CentOS-7-x86_64-Minimal-1503-01.iso",
      "IP": "192.168.0.244"
  },
  "builders": [
    {
      "type": "docker",
      "image": "centos:7",
      "export_path": "centos7.tar"
    },
    {
      "type": "virtualbox-iso",
      "vm_name": "_{{ user `vm_name` }}",
      "iso_checksum_type": "md5",
      "iso_checksum": "{{ user `iso_checksum` }}",
      "iso_url": "{{ user `iso_url` }}",
      "http_directory": ".",
      "boot_command": [
        "<tab> text ks=http://{{ user `IP` }}:{{ .HTTPPort }}/ks.cfg<enter>"
      ],
      "headless": "true",
      "guest_os_type": "RedHat_64",
      "vboxmanage": [
        [ "modifyvm", "{{.Name}}", "--memory", "2048" ],
        [ "modifyvm", "{{.Name}}", "--cpus",   "1"    ]
      ],
      "ssh_password": "centos",
      "ssh_username": "centos",
      "ssh_wait_timeout": "50000s",
      "shutdown_command": "echo 'centos' | sudo -S /sbin/halt -h -p"
    },
    {
      "type": "vmware-iso",
      "vm_name": "_{{ user `vm_name` }}",
      "iso_checksum_type": "md5",
      "iso_checksum": "{{ user `iso_checksum` }}",
      "iso_url": "{{ user `iso_url` }}",
      "http_directory": ".",
      "boot_command": [
        "<tab> text ks=http://{{ user `IP` }}:{{ .HTTPPort }}/ks.cfg<enter>"
      ],
      "headless": "true",
      "guest_os_type": "rhel7-64",
      "vmx_data": {
        "memsize": "4096",
        "numvcpus":   "1",
        "cpuid.coresPerSocket": "1",
        "scsi0.present": "true",
        "scsi0.virtualDev": "pvscsi"
      },
      "disk_size": "30000",
      "vmdk_name": "box-disk1",
      "disk_type_id": "0",
      "ssh_password": "centos",
      "ssh_username": "centos",
      "ssh_wait_timeout": "50000s",
      "shutdown_command": "echo 'centos' | sudo -S /sbin/halt -h -p"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "scripts": [
            "../common/scripts/setup-docker.sh",
            "../common/scripts/ansible.sh",
            "../common/scripts/bootstrap.sh",
            "../common/scripts/disable-selinux.sh",
            "../common/scripts/docker.sh",
            "../common/scripts/teardown.sh"
      ],
      "only": ["docker"]
    },
    {
      "type": "shell",
      "execute_command": "echo 'centos' | {{ .Vars }} sudo -E -S sh '{{ .Path }}'",
      "scripts": [
            "../common/scripts/virtualbox.guest.additions.sh",
            "../common/scripts/vagrant.guest.account.sh"
      ],
      "only": ["virtualbox-iso"]
    },
    {
      "type": "shell",
      "execute_command": "echo 'centos' | {{ .Vars }} sudo -E -S sh '{{ .Path }}'",
      "scripts": [
            "../common/scripts/vmware-tools.sh"
      ],
      "only": ["vmware-iso"]
    },
    {
      "type": "shell",
      "execute_command": "echo 'centos' | {{ .Vars }} sudo -E -S sh '{{ .Path }}'",
      "scripts": [
            "../common/scripts/ansible.sh",
            "../common/scripts/bootstrap.sh",
            "../common/scripts/disable-selinux.sh",
            "../common/scripts/sshd_config.sh"
      ],
      "only": ["virtualbox-iso", "vmware-iso"]
    }
  ],
  "post-processors": [
        {
            "type": "vagrant",
            "output": "{{ user `vm_name` }}.{{.Provider}}.box",
            "only": ["virtualbox-iso"]
        },
        {
            "type": "compress",
            "format": "tar.gz",
            "only": ["vmware-iso"]
        }
  ]
}
```

**Comment by cbednarski** [comment]
Thanks for the report. This was a bug in 0.8.0 and was fixed in 0.8.1. You can resolve this by upgrading or by removing the compress post-processor from your build template.
