### ISSUE TITLE
Packer crash on Atlas , amazon-ebs errored

### ISSUE THREAD

**Issue by CruzanCaramele** [mitchellh/packer#3103]
i was going through the example for deploying python applications from one of your repos at    https://github.com/hashicorp/atlas-examples/tree/master/metamon#step-1-build-a-consul-server-ami-with-packer 

And i got this Crash log on ATLAS stating the error is that Packer has crashed :

```
Packer v0.9.0.rc1 (25108c8d13912434d0f32faaf1ea13cdc537b21e+CHANGES)

amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name...
Build 'amazon-ebs' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: unexpected EOF

==> Builds finished but no artifacts were created.


!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/mitchellh/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
panic: runtime error: invalid memory address or nil pointer dereference
2016/01/23 13:02:56 packer: [signal 0xb code=0x1 addr=0x0 pc=0xcf1110]
2016/01/23 13:02:56 packer: 
2016/01/23 13:02:56 packer: goroutine 90 [running]:
2016/01/23 13:02:56 packer: github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMetadata(0x0, 0x13133e0, 0x19, 0x0, 0x0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:18 +0x1b0
2016/01/23 13:02:56 packer: github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.requestCredList(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:128 +0x74
2016/01/23 13:02:56 packer: github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.(*EC2RoleProvider).Retrieve(0xc82024ac90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:85 +0x7b
2016/01/23 13:02:56 packer: github.com/aws/aws-sdk-go/aws/credentials.(*ChainProvider).Retrieve(0xc82024acc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/credentials/chain_provider.go:65 +0xf2
2016/01/23 13:02:56 packer: github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).Get(0xc82018a960, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/credentials/credentials.go:182 +0x111
2016/01/23 13:02:56 packer: github.com/aws/aws-sdk-go/private/signer/v4.(*signer).sign(0xc82008b130, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/private/signer/v4/v4.go:123 +0x3bf
2016/01/23 13:02:56 packer: github.com/aws/aws-sdk-go/private/signer/v4.Sign(0xc8202358c0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/private/signer/v4/v4.go:97 +0x1e7
2016/01/23 13:02:56 packer: github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc8202359d8, 0xc8202358c0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/request/handlers.go:115 +0x9f
2016/01/23 13:02:56 packer: github.com/aws/aws-sdk-go/aws/request.(*Request).Sign(0xc8202358c0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/request/request.go:197 +0xce
2016/01/23 13:02:56 packer: github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc8202358c0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/request/request.go:207 +0x54
2016/01/23 13:02:56 packer: github.com/aws/aws-sdk-go/service/ec2.(*EC2).DescribeImages(0xc820026300, 0xc82026c0e0, 0xc82025ac40, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/service/ec2/api.go:2962 +0x4f
2016/01/23 13:02:56 packer: github.com/mitchellh/packer/builder/amazon/common.(*StepPreValidate).Run(0xc82025ac40, 0x7f16bd2cc240, 0xc82024aff0, 0x7f16bd2cc240)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/packer/builder/amazon/common/step_pre_validate.go:34 +0x3a4
2016/01/23 13:02:56 packer: github.com/mitchellh/multistep.(*BasicRunner).Run(0xc820215c00, 0x7f16bd2cc240, 0xc82024aff0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/multistep/basic_runner.go:70 +0x330
2016/01/23 13:02:56 packer: github.com/mitchellh/packer/builder/amazon/ebs.(*Builder).Run(0xc82017e000, 0x7f16bd2cbd10, 0xc82025a960, 0x7f16bd2cbd58, 0xc82025ce00, 0x7f16bd2cbd88, 0xc8200262e0, 0x0, 0x0, 0x0, ...)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/packer/builder/amazon/ebs/builder.go:171 +0x16be
2016/01/23 13:02:56 packer: github.com/mitchellh/packer/packer/rpc.(*BuilderServer).Run(0xc8201846c0, 0x1, 0xc82025cd20, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/packer/packer/rpc/builder.go:93 +0x3b9
2016/01/23 13:02:56 packer: reflect.Value.call(0xf661a0, 0x108e640, 0x13, 0x1214660, 0x4, 0xc82008bed8, 0x3, 0x3, 0x0, 0x0, ...)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/reflect/value.go:432 +0x120a
2016/01/23 13:02:56 packer: reflect.Value.Call(0xf661a0, 0x108e640, 0x13, 0xc82008bed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/reflect/value.go:300 +0xb1
2016/01/23 13:02:56 packer: net/rpc.(*service).call(0xc8200b5a80, 0xc8200b5a40, 0xc82017daa0, 0xc820079580, 0xc820184a80, 0xdf77a0, 0xc82025cd10, 0xca, 0xdc7600, 0xc82025cd20, ...)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/net/rpc/server.go:383 +0x1c1
2016/01/23 13:02:56 packer: created by net/rpc.(*Server).ServeCodec
2016/01/23 13:02:56 packer: 	/usr/local/go/src/net/rpc/server.go:477 +0x4ac
2016/01/23 13:02:56 packer: 
2016/01/23 13:02:56 packer: goroutine 1 [select]:
2016/01/23 13:02:56 packer: github.com/hashicorp/yamux.(*Stream).Read(0xc820180500, 0xc8201bf000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/hashicorp/yamux/stream.go:125 +0x3ae
2016/01/23 13:02:56 packer: bufio.(*Reader).fill(0xc8201bc0c0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
2016/01/23 13:02:56 packer: bufio.(*Reader).ReadByte(0xc8201bc0c0, 0x20, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/bufio/bufio.go:229 +0x7a
2016/01/23 13:02:56 packer: github.com/ugorji/go/codec.(*ioDecReader).readn1(0xc8201c0070, 0xc820184a80)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/ugorji/go/codec/decode.go:276 +0x41
2016/01/23 13:02:56 packer: github.com/ugorji/go/codec.(*msgpackDecDriver).readNextBd(0xc82018a280)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/ugorji/go/codec/msgpack.go:560 +0x3a
2016/01/23 13:02:56 packer: github.com/ugorji/go/codec.(*msgpackDecDriver).TryDecodeAsNil(0xc82018a280, 0xdbda00)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/ugorji/go/codec/msgpack.go:587 +0x2f
2016/01/23 13:02:56 packer: github.com/ugorji/go/codec.(*Decoder).decode(0xc8201c0000, 0xdbda60, 0xc8201847c0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/ugorji/go/codec/decode.go:1474 +0x67
2016/01/23 13:02:56 packer: github.com/ugorji/go/codec.(*Decoder).Decode(0xc8201c0000, 0xdbda60, 0xc8201847c0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/ugorji/go/codec/decode.go:1383 +0x74
2016/01/23 13:02:56 packer: github.com/ugorji/go/codec.(*rpcCodec).read(0xc8201411f0, 0xdbda60, 0xc8201847c0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/ugorji/go/codec/rpc.go:107 +0xe1
2016/01/23 13:02:56 packer: github.com/ugorji/go/codec.(*goRpcCodec).ReadRequestHeader(0xc8201411f0, 0xc8201847c0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/ugorji/go/codec/rpc.go:155 +0x54
2016/01/23 13:02:56 packer: net/rpc.(*Server).readRequestHeader(0xc8200b5a40, 0x7f16bd2c7480, 0xc8201411f0, 0x0, 0x0, 0xc8201847c0, 0xc82009f600, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/net/rpc/server.go:576 +0x90
2016/01/23 13:02:56 packer: net/rpc.(*Server).readRequest(0xc8200b5a40, 0x7f16bd2c7480, 0xc8201411f0, 0xc8200b5a40, 0xc82017daa0, 0xc820079580, 0x0, 0x0, 0x0, 0x0, ...)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/net/rpc/server.go:543 +0x8b
2016/01/23 13:02:56 packer: net/rpc.(*Server).ServeCodec(0xc8200b5a40, 0x7f16bd2c7480, 0xc8201411f0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/net/rpc/server.go:462 +0x8c
2016/01/23 13:02:56 packer: github.com/mitchellh/packer/packer/rpc.(*Server).Serve(0xc820184680)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/packer/packer/rpc/server.go:141 +0x270
2016/01/23 13:02:56 packer: github.com/mitchellh/packer/command.(*PluginCommand).Run(0xc820140f50, 0xc82000a200, 0x1, 0x1, 0xc8200afc58)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/packer/command/plugin.go:162 +0x7e0
2016/01/23 13:02:56 packer: github.com/mitchellh/cli.(*CLI).Run(0xc82015f130, 0xc82015f130, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/cli/cli.go:112 +0x655
2016/01/23 13:02:56 packer: main.wrappedMain(0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/packer/main.go:189 +0x13f4
2016/01/23 13:02:56 packer: main.realMain(0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/packer/main.go:93 +0xa88
2016/01/23 13:02:56 packer: main.main()
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/packer/main.go:28 +0x18
2016/01/23 13:02:56 packer: 
2016/01/23 13:02:56 packer: goroutine 5 [syscall]:
2016/01/23 13:02:56 packer: os/signal.loop()
2016/01/23 13:02:56 packer: 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
2016/01/23 13:02:56 packer: created by os/signal.init.1
2016/01/23 13:02:56 packer: 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
2016/01/23 13:02:56 packer: 
2016/01/23 13:02:56 packer: goroutine 13 [IO wait]:
2016/01/23 13:02:56 packer: net.runtime_pollWait(0x7f16bd2c6c30, 0x72, 0xc82000e1b0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/runtime/netpoll.go:157 +0x60
2016/01/23 13:02:56 packer: net.(*pollDesc).Wait(0xc820141100, 0x72, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
2016/01/23 13:02:56 packer: net.(*pollDesc).WaitRead(0xc820141100, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
2016/01/23 13:02:56 packer: net.(*netFD).Read(0xc8201410a0, 0xc820193000, 0x1000, 0x1000, 0x0, 0x7f16bd2c0050, 0xc82000e1b0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/net/fd_unix.go:232 +0x23a
2016/01/23 13:02:56 packer: net.(*conn).Read(0xc820026208, 0xc820193000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/net/net.go:172 +0xe4
2016/01/23 13:02:56 packer: bufio.(*Reader).fill(0xc8200139e0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
2016/01/23 13:02:56 packer: bufio.(*Reader).Read(0xc8200139e0, 0xc82017d9e0, 0xc, 0xc, 0xc82017d9e2, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/bufio/bufio.go:207 +0x260
2016/01/23 13:02:56 packer: io.ReadAtLeast(0x7f16bd2c6ee8, 0xc8200139e0, 0xc82017d9e0, 0xc, 0xc, 0xc, 0x0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/io/io.go:298 +0xe6
2016/01/23 13:02:56 packer: io.ReadFull(0x7f16bd2c6ee8, 0xc8200139e0, 0xc82017d9e0, 0xc, 0xc, 0xc, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/io/io.go:316 +0x62
2016/01/23 13:02:56 packer: github.com/hashicorp/yamux.(*Session).recvLoop(0xc82015f1e0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/hashicorp/yamux/session.go:408 +0x11e
2016/01/23 13:02:56 packer: github.com/hashicorp/yamux.(*Session).recv(0xc82015f1e0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/hashicorp/yamux/session.go:396 +0x21
2016/01/23 13:02:56 packer: created by github.com/hashicorp/yamux.newSession
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/hashicorp/yamux/session.go:104 +0x4b1
2016/01/23 13:02:56 packer: 
2016/01/23 13:02:56 packer: goroutine 12 [chan receive]:
2016/01/23 13:02:56 packer: github.com/mitchellh/packer/packer/plugin.Server.func1(0xc820013980)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/packer/packer/plugin/server.go:94 +0x66
2016/01/23 13:02:56 packer: created by github.com/mitchellh/packer/packer/plugin.Server
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/packer/packer/plugin/server.go:98 +0xcb5
2016/01/23 13:02:56 packer: 
2016/01/23 13:02:56 packer: goroutine 9 [select, locked to thread]:
2016/01/23 13:02:56 packer: runtime.gopark(0x1498eb0, 0xc820025728, 0x121d488, 0x6, 0x437418, 0x2)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/runtime/proc.go:185 +0x163
2016/01/23 13:02:56 packer: runtime.selectgoImpl(0xc820025728, 0x0, 0x18)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/runtime/select.go:392 +0xa64
2016/01/23 13:02:56 packer: runtime.selectgo(0xc820025728)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/runtime/select.go:212 +0x12
2016/01/23 13:02:56 packer: runtime.ensureSigM.func1()
2016/01/23 13:02:56 packer: 	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
2016/01/23 13:02:56 packer: runtime.goexit()
2016/01/23 13:02:56 packer: 	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
2016/01/23 13:02:56 packer: 
2016/01/23 13:02:56 packer: goroutine 10 [chan receive]:
2016/01/23 13:02:56 packer: main.setupStdin.func2(0xc820012d20, 0xc8200261c0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/packer/stdin.go:34 +0x93
2016/01/23 13:02:56 packer: created by main.setupStdin
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/packer/stdin.go:36 +0x13c
2016/01/23 13:02:56 packer: 
2016/01/23 13:02:56 packer: goroutine 14 [select]:
2016/01/23 13:02:56 packer: github.com/hashicorp/yamux.(*Session).send(0xc82015f1e0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/hashicorp/yamux/session.go:358 +0x5e1
2016/01/23 13:02:56 packer: created by github.com/hashicorp/yamux.newSession
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/hashicorp/yamux/session.go:105 +0x4d3
2016/01/23 13:02:56 packer: 
2016/01/23 13:02:56 packer: goroutine 15 [select]:
2016/01/23 13:02:56 packer: github.com/hashicorp/yamux.(*Session).keepalive(0xc82015f1e0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/hashicorp/yamux/session.go:292 +0x240
2016/01/23 13:02:56 packer: created by github.com/hashicorp/yamux.newSession
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/hashicorp/yamux/session.go:107 +0x506
2016/01/23 13:02:56 packer: 
2016/01/23 13:02:56 packer: goroutine 16 [select]:
2016/01/23 13:02:56 packer: github.com/hashicorp/yamux.(*Session).AcceptStream(0xc82015f1e0, 0x1497160, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/hashicorp/yamux/session.go:191 +0x19d
2016/01/23 13:02:56 packer: github.com/mitchellh/packer/packer/rpc.(*muxBroker).Run(0xc820184660)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/packer/packer/rpc/mux_broker.go:126 +0x34
2016/01/23 13:02:56 packer: created by github.com/mitchellh/packer/packer/rpc.NewServer
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/packer/packer/rpc/server.go:42 +0x14a
2016/01/23 13:02:56 packer: 
2016/01/23 13:02:56 packer: goroutine 92 [runnable]:
2016/01/23 13:02:56 packer: github.com/mitchellh/multistep.(*BasicRunner).Run.func2(0xc82024ed20, 0x7f16bd2cc240, 0xc82024aff0, 0xc82024ed80)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/multistep/basic_runner.go:53 +0x159
2016/01/23 13:02:56 packer: created by github.com/mitchellh/multistep.(*BasicRunner).Run
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/mitchellh/multistep/basic_runner.go:60 +0x1d9
2016/01/23 13:02:56 packer: 
2016/01/23 13:02:56 packer: goroutine 91 [runnable]:
2016/01/23 13:02:56 packer: github.com/hashicorp/yamux.(*Stream).Read(0xc820180780, 0xc82026b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/hashicorp/yamux/stream.go:125 +0x3ae
2016/01/23 13:02:56 packer: bufio.(*Reader).fill(0xc82024eba0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
2016/01/23 13:02:56 packer: bufio.(*Reader).ReadByte(0xc82024eba0, 0xac5521, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/bufio/bufio.go:229 +0x7a
2016/01/23 13:02:56 packer: github.com/ugorji/go/codec.(*ioDecReader).readn1(0xc8201c0370, 0x123e420)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/ugorji/go/codec/decode.go:276 +0x41
2016/01/23 13:02:56 packer: github.com/ugorji/go/codec.(*msgpackDecDriver).readNextBd(0xc82018a910)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/ugorji/go/codec/msgpack.go:560 +0x3a
2016/01/23 13:02:56 packer: github.com/ugorji/go/codec.(*msgpackDecDriver).TryDecodeAsNil(0xc82018a910, 0xace400)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/ugorji/go/codec/msgpack.go:587 +0x2f
2016/01/23 13:02:56 packer: github.com/ugorji/go/codec.(*Decoder).decode(0xc8201c0300, 0xdbdac0, 0xc82024b0e0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/ugorji/go/codec/decode.go:1474 +0x67
2016/01/23 13:02:56 packer: github.com/ugorji/go/codec.(*Decoder).Decode(0xc8201c0300, 0xdbdac0, 0xc82024b0e0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/ugorji/go/codec/decode.go:1383 +0x74
2016/01/23 13:02:56 packer: github.com/ugorji/go/codec.(*rpcCodec).read(0xc82026c000, 0xdbdac0, 0xc82024b0e0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/ugorji/go/codec/rpc.go:107 +0xe1
2016/01/23 13:02:56 packer: github.com/ugorji/go/codec.(*goRpcCodec).ReadResponseHeader(0xc82026c000, 0xc82024b0e0, 0x0, 0x0)
2016/01/23 13:02:56 packer: 	/Users/pearkes/code/golang/src/github.com/ugorji/go/codec/rpc.go:151 +0x54
2016/01/23 13:02:56 packer: net/rpc.(*Client).input(0xc82024ec00)
2016/01/23 13:02:56 packer: 	/usr/local/go/src/net/rpc/client.go:109 +0xbf
2016/01/23 13:02:56 packer: created by net/rpc.NewClientWithCodec
2016/01/23 13:02:56 packer: 	/usr/local/go/src/net/rpc/client.go:201 +0xd2
2016/01/23 13:02:56 /usr/local/bin/packer: plugin process exited
2016/01/23 13:02:56 ui error: Build 'amazon-ebs' errored: unexpected EOF
2016/01/23 13:02:56 Builds completed. Waiting on interrupt barrier...
2016/01/23 13:02:56 machine readable: error-count []string{"1"}
2016/01/23 13:02:56 ui error: 
==> Some builds didn't complete successfully and had errors:
2016/01/23 13:02:56 machine readable: amazon-ebs,error []string{"unexpected EOF"}
2016/01/23 13:02:56 ui error: --> amazon-ebs: unexpected EOF
2016/01/23 13:02:56 ui: 
==> Builds finished but no artifacts were created.
2016/01/23 13:02:56 waiting for all plugin processes to complete...
2016/01/23 13:02:56 /usr/local/bin/packer: plugin process exited
2016/01/23 13:02:56 /usr/local/bin/packer: plugin process exited
2016/01/23 13:02:56 /usr/local/bin/packer: plugin process exited
2016/01/23 13:02:56 /usr/local/bin/packer: plugin process exited
2016/01/23 13:02:56 /usr/local/bin/packer: plugin process exited
```

**Comment by CruzanCaramele** [comment]
I tried the same thing with Packer 0.8.6 and it works. Looks like the issue is with packer v0.9.0.rc1

**Comment by cbednarski** [comment]
Thanks for reporting this. I think this was fixed in #3123 and it should be working in 0.9 (now released). If not please let me know! Thanks.

**Comment by CruzanCaramele** [comment]
@cbednarski  sorry for the late reply, yes it works now :+1:

**Comment by cbednarski** [comment]
@CruzanCaramele Glad to hear! Thanks for following up. :)
