### ISSUE TITLE
Uploading crash.log and reporting crash per application request.

### ISSUE THREAD

**Issue by les-tallman** [mitchellh/packer#3233]
Packer Version = 0.8.6
Host = CentOS 7
VMware Workstation = 12
We were attempting to build a Windows 2012 R2 template.

[crash.log.zip](https://github.com/mitchellh/packer/files/138827/crash.log.zip)

**Comment by cbednarski** [comment]
Thanks for the report. Can you try reproducing with 0.9.0-rc2? If you can repro on the latest version, can you share a minimal repro including your template? Thanks!

Snip from the log:

```
2016/02/19 17:28:30 ui: [1;32m==> windows-2012R2: Provisioning with Powershell...[0m
2016/02/19 17:28:30 ui: [1;32m==> windows-2012R2: Provisioning with shell script: packer-templates/windows2012r2/script/vmware-iso/install_vmware_tools.ps1[0m
2016/02/19 17:28:30 packer-provisioner-powershell: 2016/02/19 17:28:30 Opening packer-templates/windows2012r2/script/vmware-iso/install_vmware_tools.ps1 for reading
2016/02/19 17:28:30 packer-provisioner-powershell: 2016/02/19 17:28:30 Building elevated command wrapper for: $env:PACKER_BUILDER_TYPE="vmware-iso"; $env:PACKER_BUILD_NAME="windows-2012R2"; C:/windows/temp/install_vmware_tools.ps1
2016/02/19 17:28:30 packer-provisioner-powershell: 2016/02/19 17:28:30 Uploading elevated shell wrapper for command [$env:PACKER_BUILDER_TYPE="vmware-iso"; $env:PACKER_BUILD_NAME="windows-2012R2"; C:/windows/temp/install_vmware_tools.ps1] to [${env:TEMP}\packer-elevated-shell-56c7970e-e7ed-43cd-0978-32cc0d7686e6.ps1] from [/tmp/packer-elevated-shell.ps1037492268]
2016/02/19 17:28:30 packer-provisioner-powershell: 2016/02/19 17:28:30 [INFO] 2612 bytes written for 'uploadData'
2016/02/19 17:28:30 [INFO] 2612 bytes written for 'uploadData'
2016/02/19 17:28:30 packer-builder-vmware-iso: 2016/02/19 17:28:30 Uploading file to '${env:TEMP}\packer-elevated-shell-56c7970e-e7ed-43cd-0978-32cc0d7686e6.ps1'
2016/02/19 17:28:32 [INFO] 994 bytes written for 'uploadData'
2016/02/19 17:28:32 packer-provisioner-powershell: 2016/02/19 17:28:32 [INFO] 994 bytes written for 'uploadData'
2016/02/19 17:28:32 packer-builder-vmware-iso: 2016/02/19 17:28:32 Uploading file to 'C:/windows/temp/install_vmware_tools.ps1'
2016/02/19 17:28:45 packer-builder-vmware-iso: panic: runtime error: invalid memory address or nil pointer dereference
2016/02/19 17:28:45 packer-builder-vmware-iso: [signal 0xb code=0x1 addr=0x58 pc=0x7e2e46]
2016/02/19 17:28:45 packer-builder-vmware-iso: 
2016/02/19 17:28:45 packer-builder-vmware-iso: goroutine 246 [running]:
2016/02/19 17:28:45 packer-builder-vmware-iso: github.com/packer-community/winrmcp/winrmcp.cleanupContent(0xc82008d280, 0xc8200170c0, 0x3a, 0x0, 0x0)
2016/02/19 17:28:45 packer-builder-vmware-iso: 	/Users/cbednarski/code/golang/src/github.com/packer-community/winrmcp/winrmcp/cp.go:160 +0x186
2016/02/19 17:28:45 packer-builder-vmware-iso: github.com/packer-community/winrmcp/winrmcp.doCopy(0xc82008d280, 0xc8201e7bd0, 0x7f32645a5da8, 0xc820376000, 0xc820167770, 0x28, 0x0, 0x0)
2016/02/19 17:28:45 packer-builder-vmware-iso: 	/Users/cbednarski/code/golang/src/github.com/packer-community/winrmcp/winrmcp/cp.go:41 +0xcb6
2016/02/19 17:28:45 packer-builder-vmware-iso: github.com/packer-community/winrmcp/winrmcp.(*Winrmcp).Write(0xc820163b90, 0xc8204c3b30, 0x28, 0x7f32645a5da8, 0xc820376000, 0x0, 0x0)
2016/02/19 17:28:45 packer-builder-vmware-iso: 	/Users/cbednarski/code/golang/src/github.com/packer-community/winrmcp/winrmcp/winrmcp.go:78 +0x8d
2016/02/19 17:28:45 packer-builder-vmware-iso: github.com/mitchellh/packer/communicator/winrm.(*Communicator).Upload(0xc820523c00, 0xc8204c3b30, 0x28, 0x7f32645a5da8, 0xc820376000, 0x0, 0x0, 0x0)
2016/02/19 17:28:45 packer-builder-vmware-iso: 	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/communicator/winrm/communicator.go:114 +0x1a8
2016/02/19 17:28:45 packer-builder-vmware-iso: github.com/mitchellh/packer/packer/rpc.(*CommunicatorServer).Upload(0xc8202950a0, 0xc820390800, 0xc820220bc0, 0x0, 0x0)
2016/02/19 17:28:45 packer-builder-vmware-iso: 	/Users/cbednarski/code/golang/src/github.com/mitchellh/packer/packer/rpc/communicator.go:237 +0x15e
2016/02/19 17:28:45 packer-builder-vmware-iso: reflect.Value.call(0x92cf60, 0x9b8380, 0x13, 0xa2c230, 0x4, 0xc820321ed8, 0x3, 0x3, 0x0, 0x0, ...)
2016/02/19 17:28:45 packer-builder-vmware-iso: 	/usr/local/go/src/reflect/value.go:432 +0x120a
2016/02/19 17:28:45 packer-builder-vmware-iso: reflect.Value.Call(0x92cf60, 0x9b8380, 0x13, 0xc820321ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/02/19 17:28:45 packer-builder-vmware-iso: 	/usr/local/go/src/reflect/value.go:300 +0xb1
2016/02/19 17:28:45 packer-builder-vmware-iso: net/rpc.(*service).call(0xc82025c480, 0xc82025c400, 0xc8203e1e40, 0xc82008c380, 0xc820523d40, 0x867f20, 0xc820390800, 0x16, 0x86ada0, 0xc820220bc0, ...)
2016/02/19 17:28:45 packer-builder-vmware-iso: 	/usr/local/go/src/net/rpc/server.go:383 +0x1c1
2016/02/19 17:28:45 packer-builder-vmware-iso: created by net/rpc.(*Server).ServeCodec
2016/02/19 17:28:45 packer-builder-vmware-iso: 	/usr/local/go/src/net/rpc/server.go:477 +0x4ac
2016/02/19 17:28:45 packer-builder-vmware-iso: 
```

**Comment by les-tallman** [comment]
We are unable to get the Packer application to respond post crash, even after a server reboot. Are there any additional "Packer" logs we can review?

**Comment by cbednarski** [comment]
Closing as #3286 is the same issue with more complete info.
