### ISSUE TITLE
Crash trying to reconnect ssh communicator

### ISSUE THREAD

**Issue by win32pro** [mitchellh/packer#3699]
[Crash Log](https://gist.github.com/cbednarski/03126c58041fb0b3c0de3dee695be208)

```
2016/07/08 12:08:20 packer: 2016/07/08 12:08:20 opening new ssh session
2016/07/08 12:08:20 packer: 2016/07/08 12:08:20 ssh session open error: 'EOF', attempting reconnect
2016/07/08 12:08:20 packer: 2016/07/08 12:08:20 reconnecting to TCP connection for SSH
2016/07/08 12:08:20 packer: 2016/07/08 12:08:20 handshaking with SSH
2016/07/08 12:08:20 packer: 2016/07/08 12:08:20 handshake complete!
2016/07/08 12:08:20 packer: 2016/07/08 12:08:20 opening new ssh session
2016/07/08 12:08:35 packer: 2016/07/08 12:08:35 ssh session open error: 'ssh: unexpected packet in response to channel open: <nil>', attempting reconnect
2016/07/08 12:08:35 packer: 2016/07/08 12:08:35 reconnecting to TCP connection for SSH
2016/07/08 12:08:35 packer: 2016/07/08 12:08:35 reconnection error: dial tcp 192.168.85.145:22: getsockopt: connection refused
2016/07/08 12:08:35 packer: panic: runtime error: invalid memory address or nil pointer dereference
2016/07/08 12:08:35 packer: [signal 0xb code=0x1 addr=0x0 pc=0x6148c0]
2016/07/08 12:08:35 packer: 
2016/07/08 12:08:35 packer: goroutine 807 [running]:
2016/07/08 12:08:35 packer: panic(0xe97f60, 0xc820010110)
2016/07/08 12:08:35 packer: 	/usr/local/go/src/runtime/panic.go:481 +0x3e6
2016/07/08 12:08:35 packer: github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh.(*Client).NewSession(0x0, 0x0, 0x0, 0x0)
2016/07/08 12:08:35 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh/client.go:129 +0x120
2016/07/08 12:08:35 packer: github.com/mitchellh/packer/communicator/ssh.(*comm).newSession(0xc8203241b0, 0x0, 0x1cbc028, 0xc820010170)
2016/07/08 12:08:35 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/communicator/ssh/communicator.go:243 +0x300
2016/07/08 12:08:35 packer: github.com/mitchellh/packer/communicator/ssh.(*comm).Start(0xc8203241b0, 0xc8204c1320, 0x0, 0x0)
2016/07/08 12:08:35 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/communicator/ssh/communicator.go:79 +0x44
2016/07/08 12:08:35 packer: github.com/mitchellh/packer/packer/rpc.(*CommunicatorServer).Start(0xc820478160, 0xc82049ce80, 0xc820320e60, 0x0, 0x0)
2016/07/08 12:08:35 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/packer/rpc/communicator.go:244 +0x872
2016/07/08 12:08:35 packer: reflect.Value.call(0xdbfba0, 0xfa4e18, 0x13, 0x110eea8, 0x4, 0xc82035fee8, 0x3, 0x3, 0x0, 0x0, ...)
2016/07/08 12:08:35 packer: 	/usr/local/go/src/reflect/value.go:435 +0x120d
2016/07/08 12:08:35 packer: reflect.Value.Call(0xdbfba0, 0xfa4e18, 0x13, 0xc82035fee8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/07/08 12:08:35 packer: 	/usr/local/go/src/reflect/value.go:303 +0xb1
2016/07/08 12:08:35 packer: net/rpc.(*service).call(0xc8202e6200, 0xc8202e6180, 0xc82036c180, 0xc820304300, 0xc8204bc220, 0xba6780, 0xc82049ce80, 0x16, 0xbb9980, 0xc820320e60, ...)
2016/07/08 12:08:35 packer: 	/usr/local/go/src/net/rpc/server.go:383 +0x1c2
2016/07/08 12:08:35 packer: created by net/rpc.(*Server).ServeCodec
2016/07/08 12:08:35 packer: 	/usr/local/go/src/net/rpc/server.go:477 +0x49d
2016/07/08 12:08:35 [ERR] Error decoding response stream 7: EOF
2016/07/08 12:08:35 ui error: [1;31mBuild 'vmware-iso' errored: unexpected EOF[0m
```

**Comment by cbednarski** [comment]
Thanks for the report. Can you share your packer template, too? Please remove any secret info before posting. Thanks!

**Comment by win32pro** [comment]
Hi,

Sorry, I can't :(

My best regards,

Michael

"Delve into the root"
~~ Kozma Prutkov

**Comment by mwhooker** [comment]
my best guess is that the nil implementation talked about [here](https://github.com/mitchellh/packer/blob/v0.10.1/communicator/ssh/communicator.go#L261-L264) is being returned without an error. This probably causes [sshConn](https://github.com/mitchellh/packer/blob/v0.10.1/communicator/ssh/communicator.go#L314) to be nil, which leaves `c.client` as nil, which causes a panic when we try to call [`c.client.NewSession`](https://github.com/mitchellh/packer/blob/v0.10.1/communicator/ssh/communicator.go#L243) with a nil receiver
