### ISSUE TITLE
Crash during cancelled build using directory upload over WinRM

### ISSUE THREAD

**Issue by deltamualpha** [mitchellh/packer#3763]
Crash after cancellation during directory upload over WinRM: https://gist.github.com/deltamualpha/06c8fd005fbe808bc55477caf9e650e1

packer.json file: https://gist.github.com/deltamualpha/01e9114aae9d3e0da4a5b73345c83ffe
```
$ packer -v
0.10.1
```

**Comment by rickard-von-essen** [comment]
Crashes on:
```
2016/07/29 16:49:32 packer: panic: runtime error: invalid memory address or nil pointer dereference
2016/07/29 16:49:32 packer: [signal 0xb code=0x1 addr=0x58 pc=0xb62506]
2016/07/29 16:49:32 packer: 
2016/07/29 16:49:32 packer: goroutine 162 [running]:
2016/07/29 16:49:32 packer: panic(0xe97f60, 0xc8200120f0)
2016/07/29 16:49:32 packer: 	/usr/local/go/src/runtime/panic.go:481 +0x3e6
2016/07/29 16:49:32 packer: github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp.cleanupContent(0xc820242480, 0xc8200de400, 0x3a, 0x0, 0x0)
2016/07/29 16:49:32 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp/cp.go:169 +0x186
2016/07/29 16:49:32 packer: github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp.doCopy(0xc820242480, 0xc82038c960, 0x1d3cbd8, 0xc820148088, 0xc820158300, 0x57, 0x0, 0x0)
2016/07/29 16:49:32 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp/cp.go:42 +0xc97
2016/07/29 16:49:32 packer: github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp.(*fileWalker).copyFile(0xc8202361e0, 0xc820405220, 0x4e, 0x1d3c8d0, 0xc820056820, 0x0, 0x0, 0x0, 0x0)
2016/07/29 16:49:32 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp/winrmcp.go:117 +0x5a9
2016/07/29 16:49:32 packer: github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp.(*fileWalker).(github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp.copyFile)-fm(0xc820405220, 0x4e, 0x1d3c8d0, 0xc820056820, 0x0, 0x0, 0x0, 0x0)
2016/07/29 16:49:32 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp/winrmcp.go:79 +0x74
2016/07/29 16:49:32 packer: path/filepath.walk(0xc820405220, 0x4e, 0x1d3c8d0, 0xc820056820, 0xc820439840, 0x0, 0x0)
2016/07/29 16:49:32 packer: 	/usr/local/go/src/path/filepath/path.go:349 +0x80
```
