### ISSUE TITLE
crash building amazon-ebs while security group is edited

### ISSUE THREAD

**Issue by sandstar** [mitchellh/packer#3798]
Packer crashed while building (with -debug) with amazon-ebs builder.  Crash appeared to happen before the provisioners (windows_shell and file types) were engaged.
I had just edited (in the AWS browser console) the EC2 security group referenced in the template's builder section, adding an inbound SSH port.

This crash seems no problem for me.  

output [crash log](https://gist.github.com/sandstar/749cf6545b33910dab9b4fa4547a7331)
- Packer Version:  0.10.1
- Host platform: Windows 7 SP1

**Comment by rickard-von-essen** [comment]
Backtrace:
```
2016/08/10 16:01:47 packer.exe: panic: interface conversion: interface {} is **ec2.Instance, not *ec2.Instance
2016/08/10 16:01:47 packer.exe: 
2016/08/10 16:01:47 packer.exe: goroutine 241 [running]:
2016/08/10 16:01:47 packer.exe: panic(0x12f20e0, 0xc08225cfc0)
2016/08/10 16:01:47 packer.exe: 	/usr/local/go/src/runtime/panic.go:481 +0x3f4
2016/08/10 16:01:47 packer.exe: github.com/mitchellh/packer/builder/amazon/common.SSHHost.func1(0x3044ca8, 0xc082262630, 0x0, 0x0, 0x0, 0x0)
2016/08/10 16:01:47 packer.exe: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/builder/amazon/common/ssh.go:19 +0x714
2016/08/10 16:01:47 packer.exe: github.com/mitchellh/packer/helper/communicator.(*StepConnectWinRM).waitForWinRM(0xc0823d9400, 0x3044ca8, 0xc082262630, 0xc082441f20, 0x0, 0x0, 0x0, 0x0)
2016/08/10 16:01:47 packer.exe: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/helper/communicator/step_connect_winrm.go:94 +0x33b
2016/08/10 16:01:47 packer.exe: github.com/mitchellh/packer/helper/communicator.(*StepConnectWinRM).Run.func1(0x3044630, 0xc08225e0c0, 0xc082002e90, 0xc082002ec0, 0xc0823d9400, 0x3044ca8, 0xc082262630, 0xc082441f20, 0xc0821c6000)
2016/08/10 16:01:47 packer.exe: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/helper/communicator/step_connect_winrm.go:41 +0x7f
2016/08/10 16:01:47 packer.exe: created by github.com/mitchellh/packer/helper/communicator.(*StepConnectWinRM).Run
2016/08/10 16:01:47 packer.exe: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/helper/communicator/step_connect_winrm.go:43 +0x1c7
2016/08/10 16:01:47 ui error: Build 'amazon-ebs' errored: unexpected EOF
2016/08/10 16:01:47 Waiting on builds to complete...
2016/08/10 16:01:47 Builds completed. Waiting on interrupt barrier...
2016/08/10 16:01:47 machine readable: error-count []string{"1"}
2016/08/10 16:01:47 ui error: 
```

**Comment by dpiddy** [comment]
Dup of https://github.com/mitchellh/packer/issues/3496?

**Comment by rickard-von-essen** [comment]
Probably, but  this one is using WinRM...

**Comment by rickard-von-essen** [comment]
Ok, yes it is. Thanks for finding these dups.
