### ISSUE TITLE
panic: interface conversion: interface {} is **ec2.Instance, not *ec2.Instance

### ISSUE THREAD

**Issue by dpiddy** [mitchellh/packer#3826]
* packer version: 0.10.1
* platform: linux amd64

Panic output:

```
==> Builds finished but no artifacts were created.
panic: interface conversion: interface {} is **ec2.Instance, not *ec2.Instance
2016/08/24 12:32:20 packer: 
2016/08/24 12:32:20 packer: goroutine 129 [running]:
2016/08/24 12:32:20 packer: panic(0x12d6880, 0xc82031cec0)
2016/08/24 12:32:20 packer:     /usr/local/go/src/runtime/panic.go:481 +0x3e6
2016/08/24 12:32:20 packer: github.com/mitchellh/packer/builder/amazon/common.SSHHost.func1(0x7fe83b225550, 0xc820384540, 0x0, 0x0, 0x0, 0x0)
2016/08/24 12:32:20 packer:     /Users/cbednarski/go/src/github.com/mitchellh/packer/builder/amazon/common/ssh.go:19 +0x70d
```

I believe this is because the state put [here](https://github.com/mitchellh/packer/blob/27cdd4480a5a0349683fe5716729000bfb1bb9ad/builder/amazon/common/ssh.go#L45) takes the address of `r.Reservations[0].Instances[0]` but that is already an `*ec2.Instance`. When the loop body runs again and the instance is pulled back out, [here](https://github.com/mitchellh/packer/blob/27cdd4480a5a0349683fe5716729000bfb1bb9ad/builder/amazon/common/ssh.go#L19), it gets an `**ec2.Instance` instead of an `*ec2.Instance`.

**Comment by rickard-von-essen** [comment]
Just checking some facts, can you run `ls -l $(dirname $(which packer))`

**Comment by dpiddy** [comment]
We run packer as part of a travis CI job, unpacking it to `~/.local/bin`. Here is what it looks like:

```
total 41448
-rwxrwxr-x 1 travis travis      814 Sep  6 23:50 aws
-rwxrwxr-x 1 travis travis      204 Sep  6 23:50 aws_bash_completer
-rwxrwxr-x 1 travis travis     1411 Sep  6 23:50 aws.cmd
-rwxrwxr-x 1 travis travis     1135 Sep  6 23:50 aws_completer
-rwxrwxr-x 1 travis travis     1915 Sep  6 23:50 aws_zsh_completer.sh
-rwxrwxr-x 1 travis travis     1674 Sep  6 23:50 jp.py
-rw-rw-r-- 1 travis travis     1842 Sep  6 23:50 jp.pyc
-rwxr-xr-x 1 travis travis 42339000 May  7 07:18 packer
-rwxrwxr-x 1 travis travis      214 Sep  6 23:50 pyrsa-decrypt
-rwxrwxr-x 1 travis travis      230 Sep  6 23:50 pyrsa-decrypt-bigfile
-rwxrwxr-x 1 travis travis      214 Sep  6 23:50 pyrsa-encrypt
-rwxrwxr-x 1 travis travis      230 Sep  6 23:50 pyrsa-encrypt-bigfile
-rwxrwxr-x 1 travis travis      212 Sep  6 23:50 pyrsa-keygen
-rwxrwxr-x 1 travis travis      235 Sep  6 23:50 pyrsa-priv2pub
-rwxrwxr-x 1 travis travis      208 Sep  6 23:50 pyrsa-sign
-rwxrwxr-x 1 travis travis      212 Sep  6 23:50 pyrsa-verify
-rwxrwxr-x 1 travis travis      593 Sep  6 23:50 rst2html.py
-rwxrwxr-x 1 travis travis      790 Sep  6 23:50 rst2latex.py
-rwxrwxr-x 1 travis travis      599 Sep  6 23:50 rst2man.py
-rwxrwxr-x 1 travis travis     1697 Sep  6 23:50 rst2odt_prepstyles.py
-rwxrwxr-x 1 travis travis      763 Sep  6 23:50 rst2odt.py
-rwxrwxr-x 1 travis travis      600 Sep  6 23:50 rst2pseudoxml.py
-rwxrwxr-x 1 travis travis      636 Sep  6 23:50 rst2s5.py
-rwxrwxr-x 1 travis travis      785 Sep  6 23:50 rst2xetex.py
-rwxrwxr-x 1 travis travis      601 Sep  6 23:50 rst2xml.py
-rwxrwxr-x 1 travis travis      669 Sep  6 23:50 rstpep2html.py
```

**Comment by dpiddy** [comment]
Seems like this is a dup of https://github.com/mitchellh/packer/issues/3496 which I didn't find before I opened this.

**Comment by rickard-von-essen** [comment]
Yes it is. Thanks for finding the dupes.
