### ISSUE TITLE
ssh_agent_auth with a pre baked key in the ami  throws 'Error cleaning up keypair. Please delete the key manually' and in the debug log 'interface is nil, not string'

### ISSUE THREAD

**Issue by stephansarver** [mitchellh/packer#4452]
Packer v0.12.2
Darwin 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64 i386
https://gist.github.com/stephansarver/52a8dec00bf4f14d20a03e05428114fc
----------------------------------------------------------------------------------

In the following logging the error is raised indicating it can not delete the keypair.

```
2017/01/24 00:59:55 ui: scan err: unexpected newline
2017/01/24 00:59:55 ui: ==> amazon-ebs: Deleting temporary keypair...
==> amazon-ebs: Deleting temporary keypair...
2017/01/24 00:59:55 ui error: ==> amazon-ebs: Error cleaning up keypair. Please delete the key manually:
==> amazon-ebs: Error cleaning up keypair. Please delete the key manually:
2017/01/24 00:59:55 ui error: ==> amazon-ebs: Error removing debug key 'ec2_amazon-ebs.pem': remove ec2_amazon-ebs.pem: no such file or directory
2017/01/24 00:59:55 ui: ask: ==> amazon-ebs: Pausing before cleanup of step 'StepSourceAMIInfo'. Press enter to continue.
==> amazon-ebs: Error removing debug key 'ec2_amazon-ebs.pem': remove ec2_amazon-ebs.pem: no such file or directory
==

```

Which looks like it could be that the code at:
https://github.com/mitchellh/packer/blob/master/builder/amazon/common/step_run_source_instance.go
line 42
`	keyName := state.Get("keyPair").(string)`

Seems like it is assuming that the state objects "keyPair" exists and is trying to call a method .(string) on it causing the panic.

Based on the documentation found here: https://www.packer.io/docs/builders/amazon-ebs.html
it was my understanding that when using the property 'ssh_agent_auth' and having a key already in the base ami authorized it should skip the temporary key pair generation.

> ssh_agent_auth (boolean) - If true, the local SSH agent will be used to authenticate connections to the source instance. No temporary keypair will be created, and the values of ssh_password and ssh_private_key_file will be ignored. To use this option with a key pair already configured in the source AMI, leave the ssh_keypair_name blank. To associate an existing key pair in AWS with the source instance, set the ssh_keypair_name field to the name of the key pair.

**Comment by rickard-von-essen** [comment]
```
2017/01/24 00:59:59 packer: panic: interface conversion: interface is nil, not string
2017/01/24 00:59:59 packer: 
2017/01/24 00:59:59 packer: goroutine 35 [running]:
2017/01/24 00:59:59 packer: panic(0x1061320, 0xc420556f00)
2017/01/24 00:59:59 packer: 	/usr/local/homebrew/Cellar/go/1.7.4_2/libexec/src/runtime/panic.go:500 +0x1a1
2017/01/24 00:59:59 packer: github.com/mitchellh/packer/builder/amazon/common.(*StepRunSourceInstance).Run(0xc42034c360, 0x1ae19e0, 0xc420490570, 0x0)
2017/01/24 00:59:59 packer: 	/private/tmp/packer-20170123-27477-ytur5f/src/github.com/mitchellh/packer/builder/amazon/common/step_run_source_instance.go:42 +0x18b
2017/01/24 00:59:59 packer: github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep.(*BasicRunner).Run(0xc420294540, 0x1ae19e0, 0xc420490570)
2017/01/24 00:59:59 packer: 	/private/tmp/packer-20170123-27477-ytur5f/src/github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep/basic_runner.go:70 +0x207
2017/01/24 00:59:59 packer: github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep.(*DebugRunner).Run(0xc420490660, 0x1ae19e0, 0xc420490570)
2017/01/24 00:59:59 packer: 	/private/tmp/packer-20170123-27477-ytur5f/src/github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep/debug_runner.go:67 +0x335
2017/01/24 00:59:59 packer: github.com/mitchellh/packer/builder/amazon/ebs.(*Builder).Run(0xc42026af00, 0x1ae43c0, 0xc420365920, 0x1adcba0, 0xc42036eb80, 0x1ae30e0, 0xc4201582a0, 0xc42037a000, 0x0, 0x0, ...)
2017/01/24 00:59:59 packer: 	/private/tmp/packer-20170123-27477-ytur5f/src/github.com/mitchellh/packer/builder/amazon/ebs/builder.go:196 +0x11cb
2017/01/24 00:59:59 packer: github.com/mitchellh/packer/packer/rpc.(*BuilderServer).Run(0xc4202906a0, 0x1, 0xc4202d0070, 0x0, 0x0)
2017/01/24 00:59:59 packer: 	/private/tmp/packer-20170123-27477-ytur5f/src/github.com/mitchellh/packer/packer/rpc/builder.go:93 +0x218
2017/01/24 00:59:59 packer: reflect.Value.call(0xc420163620, 0xc420158190, 0x13, 0x128819d, 0x4, 0xc42055fec0, 0x3, 0x3, 0x0, 0x0, ...)
2017/01/24 00:59:59 packer: 	/usr/local/homebrew/Cellar/go/1.7.4_2/libexec/src/reflect/value.go:434 +0x5c8
2017/01/24 00:59:59 packer: reflect.Value.Call(0xc420163620, 0xc420158190, 0x13, 0xc42055fec0, 0x3, 0x3, 0x16506, 0xc4202f5918, 0x1)
2017/01/24 00:59:59 packer: 	/usr/local/homebrew/Cellar/go/1.7.4_2/libexec/src/reflect/value.go:302 +0xa4
2017/01/24 00:59:59 packer: net/rpc.(*service).call(0xc4202941c0, 0xc420294180, 0xc42020bd88, 0xc42016d880, 0xc4202909e0, 0xf873e0, 0xc4202d006c, 0x18a, 0xf5b020, 0xc4202d0070, ...)
2017/01/24 00:59:59 packer: 	/usr/local/homebrew/Cellar/go/1.7.4_2/libexec/src/net/rpc/server.go:383 +0x148
2017/01/24 00:59:59 packer: created by net/rpc.(*Server).ServeCodec
2017/01/24 00:59:59 packer: 	/usr/local/homebrew/Cellar/go/1.7.4_2/libexec/src/net/rpc/server.go:477 +0x421
2017/01/24 00:59:59 ui error: [1;31mBuild 'amazon-ebs' errored: unexpected EOF[0m
```

**Comment by joshuaspence** [comment]
I am also seeing this error.

**Comment by joshuaspence** [comment]
Ah I see. So I hit this error because I had `ssh_agent_auth` set to `true` but `ssh_keypair_name` set to `""`. Setting `ssh_agent_auth` to `false` fixed it.
