### ISSUE TITLE
Packer crashes in with nil pointer dereference with workstation 12 on windows machine

### ISSUE THREAD

**Issue by spraveen** [mitchellh/packer#4465]
VMware® Workstation 12 Pro - 12.0.0 build-2985596
VMware® Workstation 12 Player - 12.0.0 build-2985596
packer - 0.12.2

Trying to build ova from vmware-vmx. Ending up with the below crash log.

```
2017/01/26 15:39:39 packer.exe: 2017/01/26 15:39:39 stdout: Total running VMs: 0
2017/01/26 15:39:39 packer.exe: 2017/01/26 15:39:39 stderr:
2017/01/26 15:39:50 packer.exe: panic: runtime error: invalid memory address or nil pointer dereference
2017/01/26 15:39:50 packer.exe: [signal 0xc0000005 code=0x0 addr=0x20 pc=0xefd976]
2017/01/26 15:39:50 packer.exe: 
2017/01/26 15:39:50 packer.exe: goroutine 57 [running]:
2017/01/26 15:39:50 packer.exe: panic(0x145d800, 0xc0420040b0)
2017/01/26 15:39:50 packer.exe: 	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1af
2017/01/26 15:39:50 packer.exe: github.com/mitchellh/packer/builder/vmware/common.NewLocalArtifact.func1(0xc04249ec80, 0x3a, 0x0, 0x0, 0x1ef0900, 0xc04252e000, 0x0, 0x0)
2017/01/26 15:39:50 packer.exe: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/builder/vmware/common/artifact.go:26 +0x36
2017/01/26 15:39:50 packer.exe: path/filepath.walk(0xc0420045d0, 0x10, 0x1f00d00, 0xc042426a80, 0xc0424107a0, 0x0, 0xc0422fae01)
2017/01/26 15:39:50 packer.exe: 	/usr/local/Cellar/go/1.7.4/libexec/src/path/filepath/path.go:372 +0x235
2017/01/26 15:39:50 packer.exe: path/filepath.Walk(0xc0420045d0, 0x10, 0xc0424107a0, 0xc0421ca7d0, 0x0)
2017/01/26 15:39:50 packer.exe: 	/usr/local/Cellar/go/1.7.4/libexec/src/path/filepath/path.go:398 +0xdc
2017/01/26 15:39:50 packer.exe: github.com/mitchellh/packer/builder/vmware/common.NewLocalArtifact(0xc0420045d0, 0x10, 0x6, 0x0, 0x0, 0xc042362a00)
2017/01/26 15:39:50 packer.exe: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/builder/vmware/common/artifact.go:33 +0xed
2017/01/26 15:39:50 packer.exe: github.com/mitchellh/packer/builder/vmware/vmx.(*Builder).Run(0xc0421a5ba0, 0x1efeba0, 0xc0423ac4a0, 0x1ef7580, 0xc0423a6af0, 0x1efd8c0, 0xc0422e2040, 0xc0422d64e0, 0x0, 0x0, ...)
2017/01/26 15:39:50 packer.exe: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/builder/vmware/vmx/builder.go:143 +0x1104
2017/01/26 15:39:50 packer.exe: github.com/mitchellh/packer/packer/rpc.(*BuilderServer).Run(0xc04213c380, 0x1, 0xc0422fc120, 0x0, 0x0)
2017/01/26 15:39:50 packer.exe: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/packer/rpc/builder.go:93 +0x21f
2017/01/26 15:39:50 packer.exe: reflect.Value.call(0xc042236720, 0xc04213a090, 0x13, 0x16aabf3, 0x4, 0xc0422a5ed0, 0x3, 0x3, 0x0, 0x0, ...)
2017/01/26 15:39:50 packer.exe: 	/usr/local/Cellar/go/1.7.4/libexec/src/reflect/value.go:434 +0x5cf
2017/01/26 15:39:50 packer.exe: reflect.Value.Call(0xc042236720, 0xc04213a090, 0x13, 0xc0422a5ed0, 0x3, 0x3, 0x415094, 0xc0422f7618, 0x1)
2017/01/26 15:39:50 packer.exe: 	/usr/local/Cellar/go/1.7.4/libexec/src/reflect/value.go:302 +0xab
2017/01/26 15:39:50 packer.exe: net/rpc.(*service).call(0xc04213e340, 0xc04213e300, 0xc042004290, 0xc042238280, 0xc04213c720, 0x13accc0, 0xc0422fc11c, 0x18a, 0x1381600, 0xc0422fc120, ...)
2017/01/26 15:39:50 packer.exe: 	/usr/local/Cellar/go/1.7.4/libexec/src/net/rpc/server.go:383 +0x14f
2017/01/26 15:39:50 packer.exe: created by net/rpc.(*Server).ServeCodec
2017/01/26 15:39:50 packer.exe: 	/usr/local/Cellar/go/1.7.4/libexec/src/net/rpc/server.go:477 +0x428
2017/01/26 15:39:50 C:\Program Files\packer_0.12.2\packer.exe: plugin process exited
2017/01/26 15:39:50 ui error: Build 'isengard-debian8' errored: unexpected EOF
2017/01/26 15:39:50 Builds completed. Waiting on interrupt barrier...
2017/01/26 15:39:50 machine readable: error-count []string{"1"}
2017/01/26 15:39:50 ui error: 
==> Some builds didn't complete successfully and had errors:
2017/01/26 15:39:50 machine readable: isengard-debian8,error []string{"unexpected EOF"}
2017/01/26 15:39:50 ui error: --> isengard-debian8: unexpected EOF
2017/01/26 15:39:50 ui: 
==> Builds finished but no artifacts were created.
2017/01/26 15:39:50 waiting for all plugin processes to complete...
```

**Comment by mwhooker** [comment]
thanks for the report! If you're seeing this error every time you run, you can try building packer with the patch in #4467 applied. That should tell you what error you're hitting
